#! /bin/sh

if [ -z "$RSCRIPT" ]
then
    RSCRIPT=Rscript
fi

if [ -z "$TADARIDAC_DIR" ]
then
    TADARIDAC_DIR=$VIGIECHIRO_DIR/Tadarida-C/tadaridaC_src
fi
if [ -z "$TADARIDAC_LEARNER_NAME" ]
then
    TADARIDAC_LEARNER_NAME=ClassifEspFrance180303.learner
fi
TADARIDAC_LEARNER_PATH=$TADARIDAC_DIR/$TADARIDAC_LEARNER_NAME

if ( [ "$#" -eq 0 ] )
then
    echo 'usage: tadaridaC <directory>'
    exit 1
else
    INPUT_FILE=`readlink -f $1`
    if ( [ "$?" -ne 0 ] )
    then
        echo "$1 is not a valid file"
        exit 1
    fi
fi


# Finally start tadaridaC R script
cd $TADARIDAC_DIR && $RSCRIPT Ta_Tc_wbuz.R $INPUT_FILE ClassifEspFrance180303.learner N 8 F T 500 0 0 ./other_inputs/SpeciesList.csv ./other_inputs/CNS_tabase3HF_France_IdConc.learner T ./other_inputs/Referentiel_seuils_ProbEspHF_.csv 500 ClassifEsp_tabase3HF_France_Cir_2019-11-26_wiSR.learner ./other_inputs/CNS_RSDB_HF_tabase3HF_sansfiltre_IdTot_wiSR_IdConc.learner ./other_inputs/Referentiel_seuils_RSDB_HF_tabase3HF_sansfiltre_IdTot_wiSR_IdConc__G.csv 1 ClassifBuzzPippip170328.learner
cd $TADARIDAC_DIR && $RSCRIPT Ta_Tc_wbuz.R $INPUT_FILE ClassifEspFrance180303.learner N 8 F T 500 0 0 ./other_inputs/SpeciesList.csv ./other_inputs/CNS_tabase3HF_France_IdConc.learner T ./other_inputs/Referentiel_seuils_ProbEspHF_.csv 500 ClassifEsp_tabase3HF_France_Cir_2019-11-26_wiSR.learner ./other_inputs/CNS_RSDB_HF_tabase3HF_sansfiltre_IdTot_wiSR_IdConc.learner ./other_inputs/Referentiel_seuils_RSDB_HF_tabase3HF_sansfiltre_IdTot_wiSR_IdConc__G.csv 2 ClassifBuzzPippip170328.learner
cd $TADARIDAC_DIR && $RSCRIPT Ta_Tc_wbuz.R $INPUT_FILE ClassifEspFrance180303.learner N 8 F T 500 0 0 ./other_inputs/SpeciesList.csv ./other_inputs/CNS_tabase3HF_France_IdConc.learner T ./other_inputs/Referentiel_seuils_ProbEspHF_.csv 500 ClassifEsp_tabase3HF_France_Cir_2019-11-26_wiSR.learner ./other_inputs/CNS_RSDB_HF_tabase3HF_sansfiltre_IdTot_wiSR_IdConc.learner ./other_inputs/Referentiel_seuils_RSDB_HF_tabase3HF_sansfiltre_IdTot_wiSR_IdConc__G.csv 3 ClassifBuzzPippip170328.learner
cd $TADARIDAC_DIR && $RSCRIPT Ta_Tc_wbuz.R $INPUT_FILE ClassifEspFrance180303.learner N 8 F T 500 0 0 ./other_inputs/SpeciesList.csv ./other_inputs/CNS_tabase3HF_France_IdConc.learner T ./other_inputs/Referentiel_seuils_ProbEspHF_.csv 500 ClassifEsp_tabase3HF_France_Cir_2019-11-26_wiSR.learner ./other_inputs/CNS_RSDB_HF_tabase3HF_sansfiltre_IdTot_wiSR_IdConc.learner ./other_inputs/Referentiel_seuils_RSDB_HF_tabase3HF_sansfiltre_IdTot_wiSR_IdConc__G.csv 4 ClassifBuzzPippip170328.learner
cd $TADARIDAC_DIR && $RSCRIPT Ta_Tc_wbuz.R $INPUT_FILE ClassifEspFrance180303.learner N 8 F T 500 0 0 ./other_inputs/SpeciesList.csv ./other_inputs/CNS_tabase3HF_France_IdConc.learner T ./other_inputs/Referentiel_seuils_ProbEspHF_.csv 500 ClassifEsp_tabase3HF_France_Cir_2019-11-26_wiSR.learner ./other_inputs/CNS_RSDB_HF_tabase3HF_sansfiltre_IdTot_wiSR_IdConc.learner ./other_inputs/Referentiel_seuils_RSDB_HF_tabase3HF_sansfiltre_IdTot_wiSR_IdConc__G.csv 5 ClassifBuzzPippip170328.learner
cd $TADARIDAC_DIR && $RSCRIPT Ta_Tc_wbuz.R $INPUT_FILE ClassifEspFrance180303.learner N 8 F T 500 0 0 ./other_inputs/SpeciesList.csv ./other_inputs/CNS_tabase3HF_France_IdConc.learner T ./other_inputs/Referentiel_seuils_ProbEspHF_.csv 500 ClassifEsp_tabase3HF_France_Cir_2019-11-26_wiSR.learner ./other_inputs/CNS_RSDB_HF_tabase3HF_sansfiltre_IdTot_wiSR_IdConc.learner ./other_inputs/Referentiel_seuils_RSDB_HF_tabase3HF_sansfiltre_IdTot_wiSR_IdConc__G.csv 6 ClassifBuzzPippip170328.learner
cd $TADARIDAC_DIR && $RSCRIPT Ta_Tc_wbuz.R $INPUT_FILE ClassifEspFrance180303.learner N 8 F T 500 0 0 ./other_inputs/SpeciesList.csv ./other_inputs/CNS_tabase3HF_France_IdConc.learner T ./other_inputs/Referentiel_seuils_ProbEspHF_.csv 500 ClassifEsp_tabase3HF_France_Cir_2019-11-26_wiSR.learner ./other_inputs/CNS_RSDB_HF_tabase3HF_sansfiltre_IdTot_wiSR_IdConc.learner ./other_inputs/Referentiel_seuils_RSDB_HF_tabase3HF_sansfiltre_IdTot_wiSR_IdConc__G.csv 7 ClassifBuzzPippip170328.learner
cd $TADARIDAC_DIR && $RSCRIPT Ta_Tc_wbuz.R $INPUT_FILE ClassifEspFrance180303.learner N 8 F T 500 0 0 ./other_inputs/SpeciesList.csv ./other_inputs/CNS_tabase3HF_France_IdConc.learner T ./other_inputs/Referentiel_seuils_ProbEspHF_.csv 500 ClassifEsp_tabase3HF_France_Cir_2019-11-26_wiSR.learner ./other_inputs/CNS_RSDB_HF_tabase3HF_sansfiltre_IdTot_wiSR_IdConc.learner ./other_inputs/Referentiel_seuils_RSDB_HF_tabase3HF_sansfiltre_IdTot_wiSR_IdConc__G.csv 8 ClassifBuzzPippip170328.learner
cd $TADARIDAC_DIR && $RSCRIPT Ta_Tc_wbuz.R $INPUT_FILE ClassifEspFrance180303.learner N 8 F T 500 0 0 ./other_inputs/SpeciesList.csv ./other_inputs/CNS_tabase3HF_France_IdConc.learner T ./other_inputs/Referentiel_seuils_ProbEspHF_.csv 500 ClassifEsp_tabase3HF_France_Cir_2019-11-26_wiSR.learner ./other_inputs/CNS_RSDB_HF_tabase3HF_sansfiltre_IdTot_wiSR_IdConc.learner ./other_inputs/Referentiel_seuils_RSDB_HF_tabase3HF_sansfiltre_IdTot_wiSR_IdConc__G.csv 9 ClassifBuzzPippip170328.learner
cd $TADARIDAC_DIR && $RSCRIPT Ta_Tc_wbuz.R $INPUT_FILE ClassifEspFrance180303.learner N 8 F T 500 0 0 ./other_inputs/SpeciesList.csv ./other_inputs/CNS_tabase3HF_France_IdConc.learner T ./other_inputs/Referentiel_seuils_ProbEspHF_.csv 500 ClassifEsp_tabase3HF_France_Cir_2019-11-26_wiSR.learner ./other_inputs/CNS_RSDB_HF_tabase3HF_sansfiltre_IdTot_wiSR_IdConc.learner ./other_inputs/Referentiel_seuils_RSDB_HF_tabase3HF_sansfiltre_IdTot_wiSR_IdConc__G.csv 10 ClassifBuzzPippip170328.learner
cd $TADARIDAC_DIR && $RSCRIPT Ta_Tc_wbuz.R $INPUT_FILE ClassifEspFrance180303.learner N 8 F T 500 0 0 ./other_inputs/SpeciesList.csv ./other_inputs/CNS_tabase3HF_France_IdConc.learner T ./other_inputs/Referentiel_seuils_ProbEspHF_.csv 500 ClassifEsp_tabase3HF_France_Cir_2019-11-26_wiSR.learner ./other_inputs/CNS_RSDB_HF_tabase3HF_sansfiltre_IdTot_wiSR_IdConc.learner ./other_inputs/Referentiel_seuils_RSDB_HF_tabase3HF_sansfiltre_IdTot_wiSR_IdConc__G.csv 11 ClassifBuzzPippip170328.learner
cd $TADARIDAC_DIR && $RSCRIPT Ta_Tc_wbuz.R $INPUT_FILE ClassifEspFrance180303.learner N 8 F T 500 0 0 ./other_inputs/SpeciesList.csv ./other_inputs/CNS_tabase3HF_France_IdConc.learner T ./other_inputs/Referentiel_seuils_ProbEspHF_.csv 500 ClassifEsp_tabase3HF_France_Cir_2019-11-26_wiSR.learner ./other_inputs/CNS_RSDB_HF_tabase3HF_sansfiltre_IdTot_wiSR_IdConc.learner ./other_inputs/Referentiel_seuils_RSDB_HF_tabase3HF_sansfiltre_IdTot_wiSR_IdConc__G.csv 12 ClassifBuzzPippip170328.learner
cd $TADARIDAC_DIR && $RSCRIPT Ta_Tc_wbuz.R $INPUT_FILE ClassifEspFrance180303.learner N 8 F T 500 0 0 ./other_inputs/SpeciesList.csv ./other_inputs/CNS_tabase3HF_France_IdConc.learner T ./other_inputs/Referentiel_seuils_ProbEspHF_.csv 500 ClassifEsp_tabase3HF_France_Cir_2019-11-26_wiSR.learner ./other_inputs/CNS_RSDB_HF_tabase3HF_sansfiltre_IdTot_wiSR_IdConc.learner ./other_inputs/Referentiel_seuils_RSDB_HF_tabase3HF_sansfiltre_IdTot_wiSR_IdConc__G.csv 13 ClassifBuzzPippip170328.learner
cd $TADARIDAC_DIR && $RSCRIPT Ta_Tc_wbuz.R $INPUT_FILE ClassifEspFrance180303.learner N 8 F T 500 0 0 ./other_inputs/SpeciesList.csv ./other_inputs/CNS_tabase3HF_France_IdConc.learner T ./other_inputs/Referentiel_seuils_ProbEspHF_.csv 500 ClassifEsp_tabase3HF_France_Cir_2019-11-26_wiSR.learner ./other_inputs/CNS_RSDB_HF_tabase3HF_sansfiltre_IdTot_wiSR_IdConc.learner ./other_inputs/Referentiel_seuils_RSDB_HF_tabase3HF_sansfiltre_IdTot_wiSR_IdConc__G.csv 14 ClassifBuzzPippip170328.learner
cd $TADARIDAC_DIR && $RSCRIPT Ta_Tc_wbuz.R $INPUT_FILE ClassifEspFrance180303.learner N 8 F T 500 0 0 ./other_inputs/SpeciesList.csv ./other_inputs/CNS_tabase3HF_France_IdConc.learner T ./other_inputs/Referentiel_seuils_ProbEspHF_.csv 500 ClassifEsp_tabase3HF_France_Cir_2019-11-26_wiSR.learner ./other_inputs/CNS_RSDB_HF_tabase3HF_sansfiltre_IdTot_wiSR_IdConc.learner ./other_inputs/Referentiel_seuils_RSDB_HF_tabase3HF_sansfiltre_IdTot_wiSR_IdConc__G.csv 15 ClassifBuzzPippip170328.learner
cd $TADARIDAC_DIR && $RSCRIPT Ta_Tc_wbuz.R $INPUT_FILE ClassifEspFrance180303.learner N 8 F T 500 0 0 ./other_inputs/SpeciesList.csv ./other_inputs/CNS_tabase3HF_France_IdConc.learner T ./other_inputs/Referentiel_seuils_ProbEspHF_.csv 500 ClassifEsp_tabase3HF_France_Cir_2019-11-26_wiSR.learner ./other_inputs/CNS_RSDB_HF_tabase3HF_sansfiltre_IdTot_wiSR_IdConc.learner ./other_inputs/Referentiel_seuils_RSDB_HF_tabase3HF_sansfiltre_IdTot_wiSR_IdConc__G.csv 16 ClassifBuzzPippip170328.learner
cd $TADARIDAC_DIR && $RSCRIPT Ta_Tc_wbuz.R $INPUT_FILE ClassifEspFrance180303.learner N 8 F T 500 0 0 ./other_inputs/SpeciesList.csv ./other_inputs/CNS_tabase3HF_France_IdConc.learner T ./other_inputs/Referentiel_seuils_ProbEspHF_.csv 500 ClassifEsp_tabase3HF_France_Cir_2019-11-26_wiSR.learner ./other_inputs/CNS_RSDB_HF_tabase3HF_sansfiltre_IdTot_wiSR_IdConc.learner ./other_inputs/Referentiel_seuils_RSDB_HF_tabase3HF_sansfiltre_IdTot_wiSR_IdConc__G.csv 17 ClassifBuzzPippip170328.learner
cd $TADARIDAC_DIR && $RSCRIPT Ta_Tc_wbuz.R $INPUT_FILE ClassifEspFrance180303.learner N 8 F T 500 0 0 ./other_inputs/SpeciesList.csv ./other_inputs/CNS_tabase3HF_France_IdConc.learner T ./other_inputs/Referentiel_seuils_ProbEspHF_.csv 500 ClassifEsp_tabase3HF_France_Cir_2019-11-26_wiSR.learner ./other_inputs/CNS_RSDB_HF_tabase3HF_sansfiltre_IdTot_wiSR_IdConc.learner ./other_inputs/Referentiel_seuils_RSDB_HF_tabase3HF_sansfiltre_IdTot_wiSR_IdConc__G.csv 18 ClassifBuzzPippip170328.learner
cd $TADARIDAC_DIR && $RSCRIPT Ta_Tc_wbuz.R $INPUT_FILE ClassifEspFrance180303.learner N 8 F T 500 0 0 ./other_inputs/SpeciesList.csv ./other_inputs/CNS_tabase3HF_France_IdConc.learner T ./other_inputs/Referentiel_seuils_ProbEspHF_.csv 500 ClassifEsp_tabase3HF_France_Cir_2019-11-26_wiSR.learner ./other_inputs/CNS_RSDB_HF_tabase3HF_sansfiltre_IdTot_wiSR_IdConc.learner ./other_inputs/Referentiel_seuils_RSDB_HF_tabase3HF_sansfiltre_IdTot_wiSR_IdConc__G.csv 19 ClassifBuzzPippip170328.learner
cd $TADARIDAC_DIR && $RSCRIPT Ta_Tc_wbuz.R $INPUT_FILE ClassifEspFrance180303.learner N 8 F T 500 0 0 ./other_inputs/SpeciesList.csv ./other_inputs/CNS_tabase3HF_France_IdConc.learner T ./other_inputs/Referentiel_seuils_ProbEspHF_.csv 500 ClassifEsp_tabase3HF_France_Cir_2019-11-26_wiSR.learner ./other_inputs/CNS_RSDB_HF_tabase3HF_sansfiltre_IdTot_wiSR_IdConc.learner ./other_inputs/Referentiel_seuils_RSDB_HF_tabase3HF_sansfiltre_IdTot_wiSR_IdConc__G.csv 20 ClassifBuzzPippip170328.learner
cd $TADARIDAC_DIR && $RSCRIPT Ta_Tc_wbuz.R $INPUT_FILE ClassifEspFrance180303.learner N 8 F T 500 0 0 ./other_inputs/SpeciesList.csv ./other_inputs/CNS_tabase3HF_France_IdConc.learner T ./other_inputs/Referentiel_seuils_ProbEspHF_.csv 500 ClassifEsp_tabase3HF_France_Cir_2019-11-26_wiSR.learner ./other_inputs/CNS_RSDB_HF_tabase3HF_sansfiltre_IdTot_wiSR_IdConc.learner ./other_inputs/Referentiel_seuils_RSDB_HF_tabase3HF_sansfiltre_IdTot_wiSR_IdConc__G.csv 21 ClassifBuzzPippip170328.learner
cd $TADARIDAC_DIR && $RSCRIPT Ta_Tc_wbuz.R $INPUT_FILE ClassifEspFrance180303.learner N 8 F T 500 0 0 ./other_inputs/SpeciesList.csv ./other_inputs/CNS_tabase3HF_France_IdConc.learner T ./other_inputs/Referentiel_seuils_ProbEspHF_.csv 500 ClassifEsp_tabase3HF_France_Cir_2019-11-26_wiSR.learner ./other_inputs/CNS_RSDB_HF_tabase3HF_sansfiltre_IdTot_wiSR_IdConc.learner ./other_inputs/Referentiel_seuils_RSDB_HF_tabase3HF_sansfiltre_IdTot_wiSR_IdConc__G.csv 22 ClassifBuzzPippip170328.learner
cd $TADARIDAC_DIR && $RSCRIPT Ta_Tc_wbuz.R $INPUT_FILE ClassifEspFrance180303.learner N 8 F T 500 0 0 ./other_inputs/SpeciesList.csv ./other_inputs/CNS_tabase3HF_France_IdConc.learner T ./other_inputs/Referentiel_seuils_ProbEspHF_.csv 500 ClassifEsp_tabase3HF_France_Cir_2019-11-26_wiSR.learner ./other_inputs/CNS_RSDB_HF_tabase3HF_sansfiltre_IdTot_wiSR_IdConc.learner ./other_inputs/Referentiel_seuils_RSDB_HF_tabase3HF_sansfiltre_IdTot_wiSR_IdConc__G.csv 23 ClassifBuzzPippip170328.learner
cd $TADARIDAC_DIR && $RSCRIPT Ta_Tc_wbuz.R $INPUT_FILE ClassifEspFrance180303.learner N 8 F T 500 0 0 ./other_inputs/SpeciesList.csv ./other_inputs/CNS_tabase3HF_France_IdConc.learner T ./other_inputs/Referentiel_seuils_ProbEspHF_.csv 500 ClassifEsp_tabase3HF_France_Cir_2019-11-26_wiSR.learner ./other_inputs/CNS_RSDB_HF_tabase3HF_sansfiltre_IdTot_wiSR_IdConc.learner ./other_inputs/Referentiel_seuils_RSDB_HF_tabase3HF_sansfiltre_IdTot_wiSR_IdConc__G.csv 24 ClassifBuzzPippip170328.learner
cd $TADARIDAC_DIR && $RSCRIPT Ta_Tc_wbuz.R $INPUT_FILE ClassifEspFrance180303.learner N 8 F T 500 0 0 ./other_inputs/SpeciesList.csv ./other_inputs/CNS_tabase3HF_France_IdConc.learner T ./other_inputs/Referentiel_seuils_ProbEspHF_.csv 500 ClassifEsp_tabase3HF_France_Cir_2019-11-26_wiSR.learner ./other_inputs/CNS_RSDB_HF_tabase3HF_sansfiltre_IdTot_wiSR_IdConc.learner ./other_inputs/Referentiel_seuils_RSDB_HF_tabase3HF_sansfiltre_IdTot_wiSR_IdConc__G.csv 25 ClassifBuzzPippip170328.learner
cd $TADARIDAC_DIR && $RSCRIPT Ta_Tc_wbuz.R $INPUT_FILE ClassifEspFrance180303.learner N 8 F T 500 0 0 ./other_inputs/SpeciesList.csv ./other_inputs/CNS_tabase3HF_France_IdConc.learner T ./other_inputs/Referentiel_seuils_ProbEspHF_.csv 500 ClassifEsp_tabase3HF_France_Cir_2019-11-26_wiSR.learner ./other_inputs/CNS_RSDB_HF_tabase3HF_sansfiltre_IdTot_wiSR_IdConc.learner ./other_inputs/Referentiel_seuils_RSDB_HF_tabase3HF_sansfiltre_IdTot_wiSR_IdConc__G.csv 26 ClassifBuzzPippip170328.learner
cd $TADARIDAC_DIR && $RSCRIPT Ta_Tc_wbuz.R $INPUT_FILE ClassifEspFrance180303.learner N 8 F T 500 0 0 ./other_inputs/SpeciesList.csv ./other_inputs/CNS_tabase3HF_France_IdConc.learner T ./other_inputs/Referentiel_seuils_ProbEspHF_.csv 500 ClassifEsp_tabase3HF_France_Cir_2019-11-26_wiSR.learner ./other_inputs/CNS_RSDB_HF_tabase3HF_sansfiltre_IdTot_wiSR_IdConc.learner ./other_inputs/Referentiel_seuils_RSDB_HF_tabase3HF_sansfiltre_IdTot_wiSR_IdConc__G.csv 27 ClassifBuzzPippip170328.learner
cd $TADARIDAC_DIR && $RSCRIPT Ta_Tc_wbuz.R $INPUT_FILE ClassifEspFrance180303.learner N 8 F T 500 0 0 ./other_inputs/SpeciesList.csv ./other_inputs/CNS_tabase3HF_France_IdConc.learner T ./other_inputs/Referentiel_seuils_ProbEspHF_.csv 500 ClassifEsp_tabase3HF_France_Cir_2019-11-26_wiSR.learner ./other_inputs/CNS_RSDB_HF_tabase3HF_sansfiltre_IdTot_wiSR_IdConc.learner ./other_inputs/Referentiel_seuils_RSDB_HF_tabase3HF_sansfiltre_IdTot_wiSR_IdConc__G.csv 28 ClassifBuzzPippip170328.learner
cd $TADARIDAC_DIR && $RSCRIPT Ta_Tc_wbuz.R $INPUT_FILE ClassifEspFrance180303.learner N 8 F T 500 0 0 ./other_inputs/SpeciesList.csv ./other_inputs/CNS_tabase3HF_France_IdConc.learner T ./other_inputs/Referentiel_seuils_ProbEspHF_.csv 500 ClassifEsp_tabase3HF_France_Cir_2019-11-26_wiSR.learner ./other_inputs/CNS_RSDB_HF_tabase3HF_sansfiltre_IdTot_wiSR_IdConc.learner ./other_inputs/Referentiel_seuils_RSDB_HF_tabase3HF_sansfiltre_IdTot_wiSR_IdConc__G.csv 29 ClassifBuzzPippip170328.learner
cd $TADARIDAC_DIR && $RSCRIPT Ta_Tc_wbuz.R $INPUT_FILE ClassifEspFrance180303.learner N 8 F T 500 0 0 ./other_inputs/SpeciesList.csv ./other_inputs/CNS_tabase3HF_France_IdConc.learner T ./other_inputs/Referentiel_seuils_ProbEspHF_.csv 500 ClassifEsp_tabase3HF_France_Cir_2019-11-26_wiSR.learner ./other_inputs/CNS_RSDB_HF_tabase3HF_sansfiltre_IdTot_wiSR_IdConc.learner ./other_inputs/Referentiel_seuils_RSDB_HF_tabase3HF_sansfiltre_IdTot_wiSR_IdConc__G.csv 30 ClassifBuzzPippip170328.learner
cd $TADARIDAC_DIR && $RSCRIPT Ta_Tc_wbuz.R $INPUT_FILE ClassifEspFrance180303.learner N 8 F T 500 0 0 ./other_inputs/SpeciesList.csv ./other_inputs/CNS_tabase3HF_France_IdConc.learner T ./other_inputs/Referentiel_seuils_ProbEspHF_.csv 500 ClassifEsp_tabase3HF_France_Cir_2019-11-26_wiSR.learner ./other_inputs/CNS_RSDB_HF_tabase3HF_sansfiltre_IdTot_wiSR_IdConc.learner ./other_inputs/Referentiel_seuils_RSDB_HF_tabase3HF_sansfiltre_IdTot_wiSR_IdConc__G.csv 31 ClassifBuzzPippip170328.learner
cd $TADARIDAC_DIR && $RSCRIPT Ta_Tc_wbuz.R $INPUT_FILE ClassifEspFrance180303.learner N 8 F T 500 0 0 ./other_inputs/SpeciesList.csv ./other_inputs/CNS_tabase3HF_France_IdConc.learner T ./other_inputs/Referentiel_seuils_ProbEspHF_.csv 500 ClassifEsp_tabase3HF_France_Cir_2019-11-26_wiSR.learner ./other_inputs/CNS_RSDB_HF_tabase3HF_sansfiltre_IdTot_wiSR_IdConc.learner ./other_inputs/Referentiel_seuils_RSDB_HF_tabase3HF_sansfiltre_IdTot_wiSR_IdConc__G.csv 32 ClassifBuzzPippip170328.learner
cd $TADARIDAC_DIR && $RSCRIPT Ta_Tc_wbuz.R $INPUT_FILE ClassifEspFrance180303.learner N 8 F T 500 0 0 ./other_inputs/SpeciesList.csv ./other_inputs/CNS_tabase3HF_France_IdConc.learner T ./other_inputs/Referentiel_seuils_ProbEspHF_.csv 500 ClassifEsp_tabase3HF_France_Cir_2019-11-26_wiSR.learner ./other_inputs/CNS_RSDB_HF_tabase3HF_sansfiltre_IdTot_wiSR_IdConc.learner ./other_inputs/Referentiel_seuils_RSDB_HF_tabase3HF_sansfiltre_IdTot_wiSR_IdConc__G.csv 33 ClassifBuzzPippip170328.learner
cd $TADARIDAC_DIR && $RSCRIPT Ta_Tc_wbuz.R $INPUT_FILE ClassifEspFrance180303.learner N 8 F T 500 0 0 ./other_inputs/SpeciesList.csv ./other_inputs/CNS_tabase3HF_France_IdConc.learner T ./other_inputs/Referentiel_seuils_ProbEspHF_.csv 500 ClassifEsp_tabase3HF_France_Cir_2019-11-26_wiSR.learner ./other_inputs/CNS_RSDB_HF_tabase3HF_sansfiltre_IdTot_wiSR_IdConc.learner ./other_inputs/Referentiel_seuils_RSDB_HF_tabase3HF_sansfiltre_IdTot_wiSR_IdConc__G.csv 34 ClassifBuzzPippip170328.learner
cd $TADARIDAC_DIR && $RSCRIPT Ta_Tc_wbuz.R $INPUT_FILE ClassifEspFrance180303.learner N 8 F T 500 0 0 ./other_inputs/SpeciesList.csv ./other_inputs/CNS_tabase3HF_France_IdConc.learner T ./other_inputs/Referentiel_seuils_ProbEspHF_.csv 500 ClassifEsp_tabase3HF_France_Cir_2019-11-26_wiSR.learner ./other_inputs/CNS_RSDB_HF_tabase3HF_sansfiltre_IdTot_wiSR_IdConc.learner ./other_inputs/Referentiel_seuils_RSDB_HF_tabase3HF_sansfiltre_IdTot_wiSR_IdConc__G.csv 35 ClassifBuzzPippip170328.learner
cd $TADARIDAC_DIR && $RSCRIPT Ta_Tc_wbuz.R $INPUT_FILE ClassifEspFrance180303.learner N 8 F T 500 0 0 ./other_inputs/SpeciesList.csv ./other_inputs/CNS_tabase3HF_France_IdConc.learner T ./other_inputs/Referentiel_seuils_ProbEspHF_.csv 500 ClassifEsp_tabase3HF_France_Cir_2019-11-26_wiSR.learner ./other_inputs/CNS_RSDB_HF_tabase3HF_sansfiltre_IdTot_wiSR_IdConc.learner ./other_inputs/Referentiel_seuils_RSDB_HF_tabase3HF_sansfiltre_IdTot_wiSR_IdConc__G.csv 36 ClassifBuzzPippip170328.learner
cd $TADARIDAC_DIR && $RSCRIPT Ta_Tc_wbuz.R $INPUT_FILE ClassifEspFrance180303.learner N 8 F T 500 0 0 ./other_inputs/SpeciesList.csv ./other_inputs/CNS_tabase3HF_France_IdConc.learner T ./other_inputs/Referentiel_seuils_ProbEspHF_.csv 500 ClassifEsp_tabase3HF_France_Cir_2019-11-26_wiSR.learner ./other_inputs/CNS_RSDB_HF_tabase3HF_sansfiltre_IdTot_wiSR_IdConc.learner ./other_inputs/Referentiel_seuils_RSDB_HF_tabase3HF_sansfiltre_IdTot_wiSR_IdConc__G.csv 37 ClassifBuzzPippip170328.learner
cd $TADARIDAC_DIR && $RSCRIPT Ta_Tc_wbuz.R $INPUT_FILE ClassifEspFrance180303.learner N 8 F T 500 0 0 ./other_inputs/SpeciesList.csv ./other_inputs/CNS_tabase3HF_France_IdConc.learner T ./other_inputs/Referentiel_seuils_ProbEspHF_.csv 500 ClassifEsp_tabase3HF_France_Cir_2019-11-26_wiSR.learner ./other_inputs/CNS_RSDB_HF_tabase3HF_sansfiltre_IdTot_wiSR_IdConc.learner ./other_inputs/Referentiel_seuils_RSDB_HF_tabase3HF_sansfiltre_IdTot_wiSR_IdConc__G.csv 38 ClassifBuzzPippip170328.learner
cd $TADARIDAC_DIR && $RSCRIPT Ta_Tc_wbuz.R $INPUT_FILE ClassifEspFrance180303.learner N 8 F T 500 0 0 ./other_inputs/SpeciesList.csv ./other_inputs/CNS_tabase3HF_France_IdConc.learner T ./other_inputs/Referentiel_seuils_ProbEspHF_.csv 500 ClassifEsp_tabase3HF_France_Cir_2019-11-26_wiSR.learner ./other_inputs/CNS_RSDB_HF_tabase3HF_sansfiltre_IdTot_wiSR_IdConc.learner ./other_inputs/Referentiel_seuils_RSDB_HF_tabase3HF_sansfiltre_IdTot_wiSR_IdConc__G.csv 39 ClassifBuzzPippip170328.learner
cd $TADARIDAC_DIR && $RSCRIPT Ta_Tc_wbuz.R $INPUT_FILE ClassifEspFrance180303.learner N 8 F T 500 0 0 ./other_inputs/SpeciesList.csv ./other_inputs/CNS_tabase3HF_France_IdConc.learner T ./other_inputs/Referentiel_seuils_ProbEspHF_.csv 500 ClassifEsp_tabase3HF_France_Cir_2019-11-26_wiSR.learner ./other_inputs/CNS_RSDB_HF_tabase3HF_sansfiltre_IdTot_wiSR_IdConc.learner ./other_inputs/Referentiel_seuils_RSDB_HF_tabase3HF_sansfiltre_IdTot_wiSR_IdConc__G.csv 40 ClassifBuzzPippip170328.learner
cd $TADARIDAC_DIR && $RSCRIPT Ta_Tc_wbuz.R $INPUT_FILE ClassifEspFrance180303.learner N 8 F T 500 0 0 ./other_inputs/SpeciesList.csv ./other_inputs/CNS_tabase3HF_France_IdConc.learner T ./other_inputs/Referentiel_seuils_ProbEspHF_.csv 500 ClassifEsp_tabase3HF_France_Cir_2019-11-26_wiSR.learner ./other_inputs/CNS_RSDB_HF_tabase3HF_sansfiltre_IdTot_wiSR_IdConc.learner ./other_inputs/Referentiel_seuils_RSDB_HF_tabase3HF_sansfiltre_IdTot_wiSR_IdConc__G.csv 41 ClassifBuzzPippip170328.learner
cd $TADARIDAC_DIR && $RSCRIPT Ta_Tc_wbuz.R $INPUT_FILE ClassifEspFrance180303.learner N 8 F T 500 0 0 ./other_inputs/SpeciesList.csv ./other_inputs/CNS_tabase3HF_France_IdConc.learner T ./other_inputs/Referentiel_seuils_ProbEspHF_.csv 500 ClassifEsp_tabase3HF_France_Cir_2019-11-26_wiSR.learner ./other_inputs/CNS_RSDB_HF_tabase3HF_sansfiltre_IdTot_wiSR_IdConc.learner ./other_inputs/Referentiel_seuils_RSDB_HF_tabase3HF_sansfiltre_IdTot_wiSR_IdConc__G.csv 42 ClassifBuzzPippip170328.learner
cd $TADARIDAC_DIR && $RSCRIPT Ta_Tc_wbuz.R $INPUT_FILE ClassifEspFrance180303.learner N 8 F T 500 0 0 ./other_inputs/SpeciesList.csv ./other_inputs/CNS_tabase3HF_France_IdConc.learner T ./other_inputs/Referentiel_seuils_ProbEspHF_.csv 500 ClassifEsp_tabase3HF_France_Cir_2019-11-26_wiSR.learner ./other_inputs/CNS_RSDB_HF_tabase3HF_sansfiltre_IdTot_wiSR_IdConc.learner ./other_inputs/Referentiel_seuils_RSDB_HF_tabase3HF_sansfiltre_IdTot_wiSR_IdConc__G.csv 43 ClassifBuzzPippip170328.learner
cd $TADARIDAC_DIR && $RSCRIPT Ta_Tc_wbuz.R $INPUT_FILE ClassifEspFrance180303.learner N 8 F T 500 0 0 ./other_inputs/SpeciesList.csv ./other_inputs/CNS_tabase3HF_France_IdConc.learner T ./other_inputs/Referentiel_seuils_ProbEspHF_.csv 500 ClassifEsp_tabase3HF_France_Cir_2019-11-26_wiSR.learner ./other_inputs/CNS_RSDB_HF_tabase3HF_sansfiltre_IdTot_wiSR_IdConc.learner ./other_inputs/Referentiel_seuils_RSDB_HF_tabase3HF_sansfiltre_IdTot_wiSR_IdConc__G.csv 44 ClassifBuzzPippip170328.learner
cd $TADARIDAC_DIR && $RSCRIPT Ta_Tc_wbuz.R $INPUT_FILE ClassifEspFrance180303.learner N 8 F T 500 0 0 ./other_inputs/SpeciesList.csv ./other_inputs/CNS_tabase3HF_France_IdConc.learner T ./other_inputs/Referentiel_seuils_ProbEspHF_.csv 500 ClassifEsp_tabase3HF_France_Cir_2019-11-26_wiSR.learner ./other_inputs/CNS_RSDB_HF_tabase3HF_sansfiltre_IdTot_wiSR_IdConc.learner ./other_inputs/Referentiel_seuils_RSDB_HF_tabase3HF_sansfiltre_IdTot_wiSR_IdConc__G.csv 45 ClassifBuzzPippip170328.learner
cd $TADARIDAC_DIR && $RSCRIPT Ta_Tc_wbuz.R $INPUT_FILE ClassifEspFrance180303.learner N 8 F T 500 0 0 ./other_inputs/SpeciesList.csv ./other_inputs/CNS_tabase3HF_France_IdConc.learner T ./other_inputs/Referentiel_seuils_ProbEspHF_.csv 500 ClassifEsp_tabase3HF_France_Cir_2019-11-26_wiSR.learner ./other_inputs/CNS_RSDB_HF_tabase3HF_sansfiltre_IdTot_wiSR_IdConc.learner ./other_inputs/Referentiel_seuils_RSDB_HF_tabase3HF_sansfiltre_IdTot_wiSR_IdConc__G.csv 46 ClassifBuzzPippip170328.learner
cd $TADARIDAC_DIR && $RSCRIPT Ta_Tc_wbuz.R $INPUT_FILE ClassifEspFrance180303.learner N 8 F T 500 0 0 ./other_inputs/SpeciesList.csv ./other_inputs/CNS_tabase3HF_France_IdConc.learner T ./other_inputs/Referentiel_seuils_ProbEspHF_.csv 500 ClassifEsp_tabase3HF_France_Cir_2019-11-26_wiSR.learner ./other_inputs/CNS_RSDB_HF_tabase3HF_sansfiltre_IdTot_wiSR_IdConc.learner ./other_inputs/Referentiel_seuils_RSDB_HF_tabase3HF_sansfiltre_IdTot_wiSR_IdConc__G.csv 47 ClassifBuzzPippip170328.learner
cd $TADARIDAC_DIR && $RSCRIPT Ta_Tc_wbuz.R $INPUT_FILE ClassifEspFrance180303.learner N 8 F T 500 0 0 ./other_inputs/SpeciesList.csv ./other_inputs/CNS_tabase3HF_France_IdConc.learner T ./other_inputs/Referentiel_seuils_ProbEspHF_.csv 500 ClassifEsp_tabase3HF_France_Cir_2019-11-26_wiSR.learner ./other_inputs/CNS_RSDB_HF_tabase3HF_sansfiltre_IdTot_wiSR_IdConc.learner ./other_inputs/Referentiel_seuils_RSDB_HF_tabase3HF_sansfiltre_IdTot_wiSR_IdConc__G.csv 48 ClassifBuzzPippip170328.learner
cd $TADARIDAC_DIR && $RSCRIPT Ta_Tc_wbuz.R $INPUT_FILE ClassifEspFrance180303.learner N 8 F T 500 0 0 ./other_inputs/SpeciesList.csv ./other_inputs/CNS_tabase3HF_France_IdConc.learner T ./other_inputs/Referentiel_seuils_ProbEspHF_.csv 500 ClassifEsp_tabase3HF_France_Cir_2019-11-26_wiSR.learner ./other_inputs/CNS_RSDB_HF_tabase3HF_sansfiltre_IdTot_wiSR_IdConc.learner ./other_inputs/Referentiel_seuils_RSDB_HF_tabase3HF_sansfiltre_IdTot_wiSR_IdConc__G.csv 49 ClassifBuzzPippip170328.learner
cd $TADARIDAC_DIR && $RSCRIPT Ta_Tc_wbuz.R $INPUT_FILE ClassifEspFrance180303.learner N 8 F T 500 0 0 ./other_inputs/SpeciesList.csv ./other_inputs/CNS_tabase3HF_France_IdConc.learner T ./other_inputs/Referentiel_seuils_ProbEspHF_.csv 500 ClassifEsp_tabase3HF_France_Cir_2019-11-26_wiSR.learner ./other_inputs/CNS_RSDB_HF_tabase3HF_sansfiltre_IdTot_wiSR_IdConc.learner ./other_inputs/Referentiel_seuils_RSDB_HF_tabase3HF_sansfiltre_IdTot_wiSR_IdConc__G.csv 50 ClassifBuzzPippip170328.learner
cd $TADARIDAC_DIR && $RSCRIPT Ta_Tc_wbuz.R $INPUT_FILE ClassifEspFrance180303.learner N 8 F T 500 0 0 ./other_inputs/SpeciesList.csv ./other_inputs/CNS_tabase3HF_France_IdConc.learner T ./other_inputs/Referentiel_seuils_ProbEspHF_.csv 500 ClassifEsp_tabase3HF_France_Cir_2019-11-26_wiSR.learner ./other_inputs/CNS_RSDB_HF_tabase3HF_sansfiltre_IdTot_wiSR_IdConc.learner ./other_inputs/Referentiel_seuils_RSDB_HF_tabase3HF_sansfiltre_IdTot_wiSR_IdConc__G.csv 51 ClassifBuzzPippip170328.learner
cd $TADARIDAC_DIR && $RSCRIPT Ta_Tc_wbuz.R $INPUT_FILE ClassifEspFrance180303.learner N 8 F T 500 0 0 ./other_inputs/SpeciesList.csv ./other_inputs/CNS_tabase3HF_France_IdConc.learner T ./other_inputs/Referentiel_seuils_ProbEspHF_.csv 500 ClassifEsp_tabase3HF_France_Cir_2019-11-26_wiSR.learner ./other_inputs/CNS_RSDB_HF_tabase3HF_sansfiltre_IdTot_wiSR_IdConc.learner ./other_inputs/Referentiel_seuils_RSDB_HF_tabase3HF_sansfiltre_IdTot_wiSR_IdConc__G.csv 52 ClassifBuzzPippip170328.learner
cd $TADARIDAC_DIR && $RSCRIPT Ta_Tc_wbuz.R $INPUT_FILE ClassifEspFrance180303.learner N 8 F T 500 0 0 ./other_inputs/SpeciesList.csv ./other_inputs/CNS_tabase3HF_France_IdConc.learner T ./other_inputs/Referentiel_seuils_ProbEspHF_.csv 500 ClassifEsp_tabase3HF_France_Cir_2019-11-26_wiSR.learner ./other_inputs/CNS_RSDB_HF_tabase3HF_sansfiltre_IdTot_wiSR_IdConc.learner ./other_inputs/Referentiel_seuils_RSDB_HF_tabase3HF_sansfiltre_IdTot_wiSR_IdConc__G.csv 53 ClassifBuzzPippip170328.learner
cd $TADARIDAC_DIR && $RSCRIPT Ta_Tc_wbuz.R $INPUT_FILE ClassifEspFrance180303.learner N 8 F T 500 0 0 ./other_inputs/SpeciesList.csv ./other_inputs/CNS_tabase3HF_France_IdConc.learner T ./other_inputs/Referentiel_seuils_ProbEspHF_.csv 500 ClassifEsp_tabase3HF_France_Cir_2019-11-26_wiSR.learner ./other_inputs/CNS_RSDB_HF_tabase3HF_sansfiltre_IdTot_wiSR_IdConc.learner ./other_inputs/Referentiel_seuils_RSDB_HF_tabase3HF_sansfiltre_IdTot_wiSR_IdConc__G.csv 54 ClassifBuzzPippip170328.learner
cd $TADARIDAC_DIR && $RSCRIPT Ta_Tc_wbuz.R $INPUT_FILE ClassifEspFrance180303.learner N 8 F T 500 0 0 ./other_inputs/SpeciesList.csv ./other_inputs/CNS_tabase3HF_France_IdConc.learner T ./other_inputs/Referentiel_seuils_ProbEspHF_.csv 500 ClassifEsp_tabase3HF_France_Cir_2019-11-26_wiSR.learner ./other_inputs/CNS_RSDB_HF_tabase3HF_sansfiltre_IdTot_wiSR_IdConc.learner ./other_inputs/Referentiel_seuils_RSDB_HF_tabase3HF_sansfiltre_IdTot_wiSR_IdConc__G.csv 55 ClassifBuzzPippip170328.learner
cd $TADARIDAC_DIR && $RSCRIPT Ta_Tc_wbuz.R $INPUT_FILE ClassifEspFrance180303.learner N 8 F T 500 0 0 ./other_inputs/SpeciesList.csv ./other_inputs/CNS_tabase3HF_France_IdConc.learner T ./other_inputs/Referentiel_seuils_ProbEspHF_.csv 500 ClassifEsp_tabase3HF_France_Cir_2019-11-26_wiSR.learner ./other_inputs/CNS_RSDB_HF_tabase3HF_sansfiltre_IdTot_wiSR_IdConc.learner ./other_inputs/Referentiel_seuils_RSDB_HF_tabase3HF_sansfiltre_IdTot_wiSR_IdConc__G.csv 56 ClassifBuzzPippip170328.learner
cd $TADARIDAC_DIR && $RSCRIPT Ta_Tc_wbuz.R $INPUT_FILE ClassifEspFrance180303.learner N 8 F T 500 0 0 ./other_inputs/SpeciesList.csv ./other_inputs/CNS_tabase3HF_France_IdConc.learner T ./other_inputs/Referentiel_seuils_ProbEspHF_.csv 500 ClassifEsp_tabase3HF_France_Cir_2019-11-26_wiSR.learner ./other_inputs/CNS_RSDB_HF_tabase3HF_sansfiltre_IdTot_wiSR_IdConc.learner ./other_inputs/Referentiel_seuils_RSDB_HF_tabase3HF_sansfiltre_IdTot_wiSR_IdConc__G.csv 57 ClassifBuzzPippip170328.learner
cd $TADARIDAC_DIR && $RSCRIPT Ta_Tc_wbuz.R $INPUT_FILE ClassifEspFrance180303.learner N 8 F T 500 0 0 ./other_inputs/SpeciesList.csv ./other_inputs/CNS_tabase3HF_France_IdConc.learner T ./other_inputs/Referentiel_seuils_ProbEspHF_.csv 500 ClassifEsp_tabase3HF_France_Cir_2019-11-26_wiSR.learner ./other_inputs/CNS_RSDB_HF_tabase3HF_sansfiltre_IdTot_wiSR_IdConc.learner ./other_inputs/Referentiel_seuils_RSDB_HF_tabase3HF_sansfiltre_IdTot_wiSR_IdConc__G.csv 58 ClassifBuzzPippip170328.learner
cd $TADARIDAC_DIR && $RSCRIPT Ta_Tc_wbuz.R $INPUT_FILE ClassifEspFrance180303.learner N 8 F T 500 0 0 ./other_inputs/SpeciesList.csv ./other_inputs/CNS_tabase3HF_France_IdConc.learner T ./other_inputs/Referentiel_seuils_ProbEspHF_.csv 500 ClassifEsp_tabase3HF_France_Cir_2019-11-26_wiSR.learner ./other_inputs/CNS_RSDB_HF_tabase3HF_sansfiltre_IdTot_wiSR_IdConc.learner ./other_inputs/Referentiel_seuils_RSDB_HF_tabase3HF_sansfiltre_IdTot_wiSR_IdConc__G.csv 59 ClassifBuzzPippip170328.learner
cd $TADARIDAC_DIR && $RSCRIPT Ta_Tc_wbuz.R $INPUT_FILE ClassifEspFrance180303.learner N 8 F T 500 0 0 ./other_inputs/SpeciesList.csv ./other_inputs/CNS_tabase3HF_France_IdConc.learner T ./other_inputs/Referentiel_seuils_ProbEspHF_.csv 500 ClassifEsp_tabase3HF_France_Cir_2019-11-26_wiSR.learner ./other_inputs/CNS_RSDB_HF_tabase3HF_sansfiltre_IdTot_wiSR_IdConc.learner ./other_inputs/Referentiel_seuils_RSDB_HF_tabase3HF_sansfiltre_IdTot_wiSR_IdConc__G.csv 60 ClassifBuzzPippip170328.learner
cd $TADARIDAC_DIR && $RSCRIPT Ta_Tc_wbuz.R $INPUT_FILE ClassifEspFrance180303.learner N 8 F T 500 0 0 ./other_inputs/SpeciesList.csv ./other_inputs/CNS_tabase3HF_France_IdConc.learner T ./other_inputs/Referentiel_seuils_ProbEspHF_.csv 500 ClassifEsp_tabase3HF_France_Cir_2019-11-26_wiSR.learner ./other_inputs/CNS_RSDB_HF_tabase3HF_sansfiltre_IdTot_wiSR_IdConc.learner ./other_inputs/Referentiel_seuils_RSDB_HF_tabase3HF_sansfiltre_IdTot_wiSR_IdConc__G.csv 61 ClassifBuzzPippip170328.learner
cd $TADARIDAC_DIR && $RSCRIPT Ta_Tc_wbuz.R $INPUT_FILE ClassifEspFrance180303.learner N 8 F T 500 0 0 ./other_inputs/SpeciesList.csv ./other_inputs/CNS_tabase3HF_France_IdConc.learner T ./other_inputs/Referentiel_seuils_ProbEspHF_.csv 500 ClassifEsp_tabase3HF_France_Cir_2019-11-26_wiSR.learner ./other_inputs/CNS_RSDB_HF_tabase3HF_sansfiltre_IdTot_wiSR_IdConc.learner ./other_inputs/Referentiel_seuils_RSDB_HF_tabase3HF_sansfiltre_IdTot_wiSR_IdConc__G.csv 62 ClassifBuzzPippip170328.learner
cd $TADARIDAC_DIR && $RSCRIPT Ta_Tc_wbuz.R $INPUT_FILE ClassifEspFrance180303.learner N 8 F T 500 0 0 ./other_inputs/SpeciesList.csv ./other_inputs/CNS_tabase3HF_France_IdConc.learner T ./other_inputs/Referentiel_seuils_ProbEspHF_.csv 500 ClassifEsp_tabase3HF_France_Cir_2019-11-26_wiSR.learner ./other_inputs/CNS_RSDB_HF_tabase3HF_sansfiltre_IdTot_wiSR_IdConc.learner ./other_inputs/Referentiel_seuils_RSDB_HF_tabase3HF_sansfiltre_IdTot_wiSR_IdConc__G.csv 63 ClassifBuzzPippip170328.learner
cd $TADARIDAC_DIR && $RSCRIPT Ta_Tc_wbuz.R $INPUT_FILE ClassifEspFrance180303.learner N 8 F T 500 0 0 ./other_inputs/SpeciesList.csv ./other_inputs/CNS_tabase3HF_France_IdConc.learner T ./other_inputs/Referentiel_seuils_ProbEspHF_.csv 500 ClassifEsp_tabase3HF_France_Cir_2019-11-26_wiSR.learner ./other_inputs/CNS_RSDB_HF_tabase3HF_sansfiltre_IdTot_wiSR_IdConc.learner ./other_inputs/Referentiel_seuils_RSDB_HF_tabase3HF_sansfiltre_IdTot_wiSR_IdConc__G.csv 64 ClassifBuzzPippip170328.learner
cd $TADARIDAC_DIR && $RSCRIPT Ta_Tc_wbuz.R $INPUT_FILE ClassifEspFrance180303.learner N 8 F T 500 0 0 ./other_inputs/SpeciesList.csv ./other_inputs/CNS_tabase3HF_France_IdConc.learner T ./other_inputs/Referentiel_seuils_ProbEspHF_.csv 500 ClassifEsp_tabase3HF_France_Cir_2019-11-26_wiSR.learner ./other_inputs/CNS_RSDB_HF_tabase3HF_sansfiltre_IdTot_wiSR_IdConc.learner ./other_inputs/Referentiel_seuils_RSDB_HF_tabase3HF_sansfiltre_IdTot_wiSR_IdConc__G.csv 65 ClassifBuzzPippip170328.learner
cd $TADARIDAC_DIR && $RSCRIPT Ta_Tc_wbuz.R $INPUT_FILE ClassifEspFrance180303.learner N 8 F T 500 0 0 ./other_inputs/SpeciesList.csv ./other_inputs/CNS_tabase3HF_France_IdConc.learner T ./other_inputs/Referentiel_seuils_ProbEspHF_.csv 500 ClassifEsp_tabase3HF_France_Cir_2019-11-26_wiSR.learner ./other_inputs/CNS_RSDB_HF_tabase3HF_sansfiltre_IdTot_wiSR_IdConc.learner ./other_inputs/Referentiel_seuils_RSDB_HF_tabase3HF_sansfiltre_IdTot_wiSR_IdConc__G.csv 66 ClassifBuzzPippip170328.learner
cd $TADARIDAC_DIR && $RSCRIPT Ta_Tc_wbuz.R $INPUT_FILE ClassifEspFrance180303.learner N 8 F T 500 0 0 ./other_inputs/SpeciesList.csv ./other_inputs/CNS_tabase3HF_France_IdConc.learner T ./other_inputs/Referentiel_seuils_ProbEspHF_.csv 500 ClassifEsp_tabase3HF_France_Cir_2019-11-26_wiSR.learner ./other_inputs/CNS_RSDB_HF_tabase3HF_sansfiltre_IdTot_wiSR_IdConc.learner ./other_inputs/Referentiel_seuils_RSDB_HF_tabase3HF_sansfiltre_IdTot_wiSR_IdConc__G.csv 67 ClassifBuzzPippip170328.learner
cd $TADARIDAC_DIR && $RSCRIPT Ta_Tc_wbuz.R $INPUT_FILE ClassifEspFrance180303.learner N 8 F T 500 0 0 ./other_inputs/SpeciesList.csv ./other_inputs/CNS_tabase3HF_France_IdConc.learner T ./other_inputs/Referentiel_seuils_ProbEspHF_.csv 500 ClassifEsp_tabase3HF_France_Cir_2019-11-26_wiSR.learner ./other_inputs/CNS_RSDB_HF_tabase3HF_sansfiltre_IdTot_wiSR_IdConc.learner ./other_inputs/Referentiel_seuils_RSDB_HF_tabase3HF_sansfiltre_IdTot_wiSR_IdConc__G.csv 68 ClassifBuzzPippip170328.learner
cd $TADARIDAC_DIR && $RSCRIPT Ta_Tc_wbuz.R $INPUT_FILE ClassifEspFrance180303.learner N 8 F T 500 0 0 ./other_inputs/SpeciesList.csv ./other_inputs/CNS_tabase3HF_France_IdConc.learner T ./other_inputs/Referentiel_seuils_ProbEspHF_.csv 500 ClassifEsp_tabase3HF_France_Cir_2019-11-26_wiSR.learner ./other_inputs/CNS_RSDB_HF_tabase3HF_sansfiltre_IdTot_wiSR_IdConc.learner ./other_inputs/Referentiel_seuils_RSDB_HF_tabase3HF_sansfiltre_IdTot_wiSR_IdConc__G.csv 69 ClassifBuzzPippip170328.learner
cd $TADARIDAC_DIR && $RSCRIPT Ta_Tc_wbuz.R $INPUT_FILE ClassifEspFrance180303.learner N 8 F T 500 0 0 ./other_inputs/SpeciesList.csv ./other_inputs/CNS_tabase3HF_France_IdConc.learner T ./other_inputs/Referentiel_seuils_ProbEspHF_.csv 500 ClassifEsp_tabase3HF_France_Cir_2019-11-26_wiSR.learner ./other_inputs/CNS_RSDB_HF_tabase3HF_sansfiltre_IdTot_wiSR_IdConc.learner ./other_inputs/Referentiel_seuils_RSDB_HF_tabase3HF_sansfiltre_IdTot_wiSR_IdConc__G.csv 70 ClassifBuzzPippip170328.learner
cd $TADARIDAC_DIR && $RSCRIPT Ta_Tc_wbuz.R $INPUT_FILE ClassifEspFrance180303.learner N 8 F T 500 0 0 ./other_inputs/SpeciesList.csv ./other_inputs/CNS_tabase3HF_France_IdConc.learner T ./other_inputs/Referentiel_seuils_ProbEspHF_.csv 500 ClassifEsp_tabase3HF_France_Cir_2019-11-26_wiSR.learner ./other_inputs/CNS_RSDB_HF_tabase3HF_sansfiltre_IdTot_wiSR_IdConc.learner ./other_inputs/Referentiel_seuils_RSDB_HF_tabase3HF_sansfiltre_IdTot_wiSR_IdConc__G.csv 71 ClassifBuzzPippip170328.learner
cd $TADARIDAC_DIR && $RSCRIPT Ta_Tc_wbuz.R $INPUT_FILE ClassifEspFrance180303.learner N 8 F T 500 0 0 ./other_inputs/SpeciesList.csv ./other_inputs/CNS_tabase3HF_France_IdConc.learner T ./other_inputs/Referentiel_seuils_ProbEspHF_.csv 500 ClassifEsp_tabase3HF_France_Cir_2019-11-26_wiSR.learner ./other_inputs/CNS_RSDB_HF_tabase3HF_sansfiltre_IdTot_wiSR_IdConc.learner ./other_inputs/Referentiel_seuils_RSDB_HF_tabase3HF_sansfiltre_IdTot_wiSR_IdConc__G.csv 72 ClassifBuzzPippip170328.learner
cd $TADARIDAC_DIR && $RSCRIPT Ta_Tc_wbuz.R $INPUT_FILE ClassifEspFrance180303.learner N 8 F T 500 0 0 ./other_inputs/SpeciesList.csv ./other_inputs/CNS_tabase3HF_France_IdConc.learner T ./other_inputs/Referentiel_seuils_ProbEspHF_.csv 500 ClassifEsp_tabase3HF_France_Cir_2019-11-26_wiSR.learner ./other_inputs/CNS_RSDB_HF_tabase3HF_sansfiltre_IdTot_wiSR_IdConc.learner ./other_inputs/Referentiel_seuils_RSDB_HF_tabase3HF_sansfiltre_IdTot_wiSR_IdConc__G.csv 73 ClassifBuzzPippip170328.learner
cd $TADARIDAC_DIR && $RSCRIPT Ta_Tc_wbuz.R $INPUT_FILE ClassifEspFrance180303.learner N 8 F T 500 0 0 ./other_inputs/SpeciesList.csv ./other_inputs/CNS_tabase3HF_France_IdConc.learner T ./other_inputs/Referentiel_seuils_ProbEspHF_.csv 500 ClassifEsp_tabase3HF_France_Cir_2019-11-26_wiSR.learner ./other_inputs/CNS_RSDB_HF_tabase3HF_sansfiltre_IdTot_wiSR_IdConc.learner ./other_inputs/Referentiel_seuils_RSDB_HF_tabase3HF_sansfiltre_IdTot_wiSR_IdConc__G.csv 74 ClassifBuzzPippip170328.learner
cd $TADARIDAC_DIR && $RSCRIPT Ta_Tc_wbuz.R $INPUT_FILE ClassifEspFrance180303.learner N 8 F T 500 0 0 ./other_inputs/SpeciesList.csv ./other_inputs/CNS_tabase3HF_France_IdConc.learner T ./other_inputs/Referentiel_seuils_ProbEspHF_.csv 500 ClassifEsp_tabase3HF_France_Cir_2019-11-26_wiSR.learner ./other_inputs/CNS_RSDB_HF_tabase3HF_sansfiltre_IdTot_wiSR_IdConc.learner ./other_inputs/Referentiel_seuils_RSDB_HF_tabase3HF_sansfiltre_IdTot_wiSR_IdConc__G.csv 75 ClassifBuzzPippip170328.learner
cd $TADARIDAC_DIR && $RSCRIPT Ta_Tc_wbuz.R $INPUT_FILE ClassifEspFrance180303.learner N 8 F T 500 0 0 ./other_inputs/SpeciesList.csv ./other_inputs/CNS_tabase3HF_France_IdConc.learner T ./other_inputs/Referentiel_seuils_ProbEspHF_.csv 500 ClassifEsp_tabase3HF_France_Cir_2019-11-26_wiSR.learner ./other_inputs/CNS_RSDB_HF_tabase3HF_sansfiltre_IdTot_wiSR_IdConc.learner ./other_inputs/Referentiel_seuils_RSDB_HF_tabase3HF_sansfiltre_IdTot_wiSR_IdConc__G.csv 76 ClassifBuzzPippip170328.learner
cd $TADARIDAC_DIR && $RSCRIPT Ta_Tc_wbuz.R $INPUT_FILE ClassifEspFrance180303.learner N 8 F T 500 0 0 ./other_inputs/SpeciesList.csv ./other_inputs/CNS_tabase3HF_France_IdConc.learner T ./other_inputs/Referentiel_seuils_ProbEspHF_.csv 500 ClassifEsp_tabase3HF_France_Cir_2019-11-26_wiSR.learner ./other_inputs/CNS_RSDB_HF_tabase3HF_sansfiltre_IdTot_wiSR_IdConc.learner ./other_inputs/Referentiel_seuils_RSDB_HF_tabase3HF_sansfiltre_IdTot_wiSR_IdConc__G.csv 77 ClassifBuzzPippip170328.learner
cd $TADARIDAC_DIR && $RSCRIPT Ta_Tc_wbuz.R $INPUT_FILE ClassifEspFrance180303.learner N 8 F T 500 0 0 ./other_inputs/SpeciesList.csv ./other_inputs/CNS_tabase3HF_France_IdConc.learner T ./other_inputs/Referentiel_seuils_ProbEspHF_.csv 500 ClassifEsp_tabase3HF_France_Cir_2019-11-26_wiSR.learner ./other_inputs/CNS_RSDB_HF_tabase3HF_sansfiltre_IdTot_wiSR_IdConc.learner ./other_inputs/Referentiel_seuils_RSDB_HF_tabase3HF_sansfiltre_IdTot_wiSR_IdConc__G.csv 78 ClassifBuzzPippip170328.learner
cd $TADARIDAC_DIR && $RSCRIPT Ta_Tc_wbuz.R $INPUT_FILE ClassifEspFrance180303.learner N 8 F T 500 0 0 ./other_inputs/SpeciesList.csv ./other_inputs/CNS_tabase3HF_France_IdConc.learner T ./other_inputs/Referentiel_seuils_ProbEspHF_.csv 500 ClassifEsp_tabase3HF_France_Cir_2019-11-26_wiSR.learner ./other_inputs/CNS_RSDB_HF_tabase3HF_sansfiltre_IdTot_wiSR_IdConc.learner ./other_inputs/Referentiel_seuils_RSDB_HF_tabase3HF_sansfiltre_IdTot_wiSR_IdConc__G.csv 79 ClassifBuzzPippip170328.learner
cd $TADARIDAC_DIR && $RSCRIPT Ta_Tc_wbuz.R $INPUT_FILE ClassifEspFrance180303.learner N 8 F T 500 0 0 ./other_inputs/SpeciesList.csv ./other_inputs/CNS_tabase3HF_France_IdConc.learner T ./other_inputs/Referentiel_seuils_ProbEspHF_.csv 500 ClassifEsp_tabase3HF_France_Cir_2019-11-26_wiSR.learner ./other_inputs/CNS_RSDB_HF_tabase3HF_sansfiltre_IdTot_wiSR_IdConc.learner ./other_inputs/Referentiel_seuils_RSDB_HF_tabase3HF_sansfiltre_IdTot_wiSR_IdConc__G.csv 80 ClassifBuzzPippip170328.learner
cd $TADARIDAC_DIR && $RSCRIPT Ta_Tc_wbuz.R $INPUT_FILE ClassifEspFrance180303.learner N 8 F T 500 0 0 ./other_inputs/SpeciesList.csv ./other_inputs/CNS_tabase3HF_France_IdConc.learner T ./other_inputs/Referentiel_seuils_ProbEspHF_.csv 500 ClassifEsp_tabase3HF_France_Cir_2019-11-26_wiSR.learner ./other_inputs/CNS_RSDB_HF_tabase3HF_sansfiltre_IdTot_wiSR_IdConc.learner ./other_inputs/Referentiel_seuils_RSDB_HF_tabase3HF_sansfiltre_IdTot_wiSR_IdConc__G.csv 81 ClassifBuzzPippip170328.learner
cd $TADARIDAC_DIR && $RSCRIPT Ta_Tc_wbuz.R $INPUT_FILE ClassifEspFrance180303.learner N 8 F T 500 0 0 ./other_inputs/SpeciesList.csv ./other_inputs/CNS_tabase3HF_France_IdConc.learner T ./other_inputs/Referentiel_seuils_ProbEspHF_.csv 500 ClassifEsp_tabase3HF_France_Cir_2019-11-26_wiSR.learner ./other_inputs/CNS_RSDB_HF_tabase3HF_sansfiltre_IdTot_wiSR_IdConc.learner ./other_inputs/Referentiel_seuils_RSDB_HF_tabase3HF_sansfiltre_IdTot_wiSR_IdConc__G.csv 82 ClassifBuzzPippip170328.learner
cd $TADARIDAC_DIR && $RSCRIPT Ta_Tc_wbuz.R $INPUT_FILE ClassifEspFrance180303.learner N 8 F T 500 0 0 ./other_inputs/SpeciesList.csv ./other_inputs/CNS_tabase3HF_France_IdConc.learner T ./other_inputs/Referentiel_seuils_ProbEspHF_.csv 500 ClassifEsp_tabase3HF_France_Cir_2019-11-26_wiSR.learner ./other_inputs/CNS_RSDB_HF_tabase3HF_sansfiltre_IdTot_wiSR_IdConc.learner ./other_inputs/Referentiel_seuils_RSDB_HF_tabase3HF_sansfiltre_IdTot_wiSR_IdConc__G.csv 83 ClassifBuzzPippip170328.learner
cd $TADARIDAC_DIR && $RSCRIPT Ta_Tc_wbuz.R $INPUT_FILE ClassifEspFrance180303.learner N 8 F T 500 0 0 ./other_inputs/SpeciesList.csv ./other_inputs/CNS_tabase3HF_France_IdConc.learner T ./other_inputs/Referentiel_seuils_ProbEspHF_.csv 500 ClassifEsp_tabase3HF_France_Cir_2019-11-26_wiSR.learner ./other_inputs/CNS_RSDB_HF_tabase3HF_sansfiltre_IdTot_wiSR_IdConc.learner ./other_inputs/Referentiel_seuils_RSDB_HF_tabase3HF_sansfiltre_IdTot_wiSR_IdConc__G.csv 84 ClassifBuzzPippip170328.learner
cd $TADARIDAC_DIR && $RSCRIPT Ta_Tc_wbuz.R $INPUT_FILE ClassifEspFrance180303.learner N 8 F T 500 0 0 ./other_inputs/SpeciesList.csv ./other_inputs/CNS_tabase3HF_France_IdConc.learner T ./other_inputs/Referentiel_seuils_ProbEspHF_.csv 500 ClassifEsp_tabase3HF_France_Cir_2019-11-26_wiSR.learner ./other_inputs/CNS_RSDB_HF_tabase3HF_sansfiltre_IdTot_wiSR_IdConc.learner ./other_inputs/Referentiel_seuils_RSDB_HF_tabase3HF_sansfiltre_IdTot_wiSR_IdConc__G.csv 85 ClassifBuzzPippip170328.learner
cd $TADARIDAC_DIR && $RSCRIPT Ta_Tc_wbuz.R $INPUT_FILE ClassifEspFrance180303.learner N 8 F T 500 0 0 ./other_inputs/SpeciesList.csv ./other_inputs/CNS_tabase3HF_France_IdConc.learner T ./other_inputs/Referentiel_seuils_ProbEspHF_.csv 500 ClassifEsp_tabase3HF_France_Cir_2019-11-26_wiSR.learner ./other_inputs/CNS_RSDB_HF_tabase3HF_sansfiltre_IdTot_wiSR_IdConc.learner ./other_inputs/Referentiel_seuils_RSDB_HF_tabase3HF_sansfiltre_IdTot_wiSR_IdConc__G.csv 86 ClassifBuzzPippip170328.learner
cd $TADARIDAC_DIR && $RSCRIPT Ta_Tc_wbuz.R $INPUT_FILE ClassifEspFrance180303.learner N 8 F T 500 0 0 ./other_inputs/SpeciesList.csv ./other_inputs/CNS_tabase3HF_France_IdConc.learner T ./other_inputs/Referentiel_seuils_ProbEspHF_.csv 500 ClassifEsp_tabase3HF_France_Cir_2019-11-26_wiSR.learner ./other_inputs/CNS_RSDB_HF_tabase3HF_sansfiltre_IdTot_wiSR_IdConc.learner ./other_inputs/Referentiel_seuils_RSDB_HF_tabase3HF_sansfiltre_IdTot_wiSR_IdConc__G.csv 87 ClassifBuzzPippip170328.learner
cd $TADARIDAC_DIR && $RSCRIPT Ta_Tc_wbuz.R $INPUT_FILE ClassifEspFrance180303.learner N 8 F T 500 0 0 ./other_inputs/SpeciesList.csv ./other_inputs/CNS_tabase3HF_France_IdConc.learner T ./other_inputs/Referentiel_seuils_ProbEspHF_.csv 500 ClassifEsp_tabase3HF_France_Cir_2019-11-26_wiSR.learner ./other_inputs/CNS_RSDB_HF_tabase3HF_sansfiltre_IdTot_wiSR_IdConc.learner ./other_inputs/Referentiel_seuils_RSDB_HF_tabase3HF_sansfiltre_IdTot_wiSR_IdConc__G.csv 88 ClassifBuzzPippip170328.learner
cd $TADARIDAC_DIR && $RSCRIPT Ta_Tc_wbuz.R $INPUT_FILE ClassifEspFrance180303.learner N 8 F T 500 0 0 ./other_inputs/SpeciesList.csv ./other_inputs/CNS_tabase3HF_France_IdConc.learner T ./other_inputs/Referentiel_seuils_ProbEspHF_.csv 500 ClassifEsp_tabase3HF_France_Cir_2019-11-26_wiSR.learner ./other_inputs/CNS_RSDB_HF_tabase3HF_sansfiltre_IdTot_wiSR_IdConc.learner ./other_inputs/Referentiel_seuils_RSDB_HF_tabase3HF_sansfiltre_IdTot_wiSR_IdConc__G.csv 89 ClassifBuzzPippip170328.learner
cd $TADARIDAC_DIR && $RSCRIPT Ta_Tc_wbuz.R $INPUT_FILE ClassifEspFrance180303.learner N 8 F T 500 0 0 ./other_inputs/SpeciesList.csv ./other_inputs/CNS_tabase3HF_France_IdConc.learner T ./other_inputs/Referentiel_seuils_ProbEspHF_.csv 500 ClassifEsp_tabase3HF_France_Cir_2019-11-26_wiSR.learner ./other_inputs/CNS_RSDB_HF_tabase3HF_sansfiltre_IdTot_wiSR_IdConc.learner ./other_inputs/Referentiel_seuils_RSDB_HF_tabase3HF_sansfiltre_IdTot_wiSR_IdConc__G.csv 90 ClassifBuzzPippip170328.learner
cd $TADARIDAC_DIR && $RSCRIPT Ta_Tc_wbuz.R $INPUT_FILE ClassifEspFrance180303.learner N 8 F T 500 0 0 ./other_inputs/SpeciesList.csv ./other_inputs/CNS_tabase3HF_France_IdConc.learner T ./other_inputs/Referentiel_seuils_ProbEspHF_.csv 500 ClassifEsp_tabase3HF_France_Cir_2019-11-26_wiSR.learner ./other_inputs/CNS_RSDB_HF_tabase3HF_sansfiltre_IdTot_wiSR_IdConc.learner ./other_inputs/Referentiel_seuils_RSDB_HF_tabase3HF_sansfiltre_IdTot_wiSR_IdConc__G.csv 91 ClassifBuzzPippip170328.learner
cd $TADARIDAC_DIR && $RSCRIPT Ta_Tc_wbuz.R $INPUT_FILE ClassifEspFrance180303.learner N 8 F T 500 0 0 ./other_inputs/SpeciesList.csv ./other_inputs/CNS_tabase3HF_France_IdConc.learner T ./other_inputs/Referentiel_seuils_ProbEspHF_.csv 500 ClassifEsp_tabase3HF_France_Cir_2019-11-26_wiSR.learner ./other_inputs/CNS_RSDB_HF_tabase3HF_sansfiltre_IdTot_wiSR_IdConc.learner ./other_inputs/Referentiel_seuils_RSDB_HF_tabase3HF_sansfiltre_IdTot_wiSR_IdConc__G.csv 92 ClassifBuzzPippip170328.learner
cd $TADARIDAC_DIR && $RSCRIPT Ta_Tc_wbuz.R $INPUT_FILE ClassifEspFrance180303.learner N 8 F T 500 0 0 ./other_inputs/SpeciesList.csv ./other_inputs/CNS_tabase3HF_France_IdConc.learner T ./other_inputs/Referentiel_seuils_ProbEspHF_.csv 500 ClassifEsp_tabase3HF_France_Cir_2019-11-26_wiSR.learner ./other_inputs/CNS_RSDB_HF_tabase3HF_sansfiltre_IdTot_wiSR_IdConc.learner ./other_inputs/Referentiel_seuils_RSDB_HF_tabase3HF_sansfiltre_IdTot_wiSR_IdConc__G.csv 93 ClassifBuzzPippip170328.learner
cd $TADARIDAC_DIR && $RSCRIPT Ta_Tc_wbuz.R $INPUT_FILE ClassifEspFrance180303.learner N 8 F T 500 0 0 ./other_inputs/SpeciesList.csv ./other_inputs/CNS_tabase3HF_France_IdConc.learner T ./other_inputs/Referentiel_seuils_ProbEspHF_.csv 500 ClassifEsp_tabase3HF_France_Cir_2019-11-26_wiSR.learner ./other_inputs/CNS_RSDB_HF_tabase3HF_sansfiltre_IdTot_wiSR_IdConc.learner ./other_inputs/Referentiel_seuils_RSDB_HF_tabase3HF_sansfiltre_IdTot_wiSR_IdConc__G.csv 94 ClassifBuzzPippip170328.learner
cd $TADARIDAC_DIR && $RSCRIPT Ta_Tc_wbuz.R $INPUT_FILE ClassifEspFrance180303.learner N 8 F T 500 0 0 ./other_inputs/SpeciesList.csv ./other_inputs/CNS_tabase3HF_France_IdConc.learner T ./other_inputs/Referentiel_seuils_ProbEspHF_.csv 500 ClassifEsp_tabase3HF_France_Cir_2019-11-26_wiSR.learner ./other_inputs/CNS_RSDB_HF_tabase3HF_sansfiltre_IdTot_wiSR_IdConc.learner ./other_inputs/Referentiel_seuils_RSDB_HF_tabase3HF_sansfiltre_IdTot_wiSR_IdConc__G.csv 95 ClassifBuzzPippip170328.learner
cd $TADARIDAC_DIR && $RSCRIPT Ta_Tc_wbuz.R $INPUT_FILE ClassifEspFrance180303.learner N 8 F T 500 0 0 ./other_inputs/SpeciesList.csv ./other_inputs/CNS_tabase3HF_France_IdConc.learner T ./other_inputs/Referentiel_seuils_ProbEspHF_.csv 500 ClassifEsp_tabase3HF_France_Cir_2019-11-26_wiSR.learner ./other_inputs/CNS_RSDB_HF_tabase3HF_sansfiltre_IdTot_wiSR_IdConc.learner ./other_inputs/Referentiel_seuils_RSDB_HF_tabase3HF_sansfiltre_IdTot_wiSR_IdConc__G.csv 96 ClassifBuzzPippip170328.learner
cd $TADARIDAC_DIR && $RSCRIPT Ta_Tc_wbuz.R $INPUT_FILE ClassifEspFrance180303.learner N 8 F T 500 0 0 ./other_inputs/SpeciesList.csv ./other_inputs/CNS_tabase3HF_France_IdConc.learner T ./other_inputs/Referentiel_seuils_ProbEspHF_.csv 500 ClassifEsp_tabase3HF_France_Cir_2019-11-26_wiSR.learner ./other_inputs/CNS_RSDB_HF_tabase3HF_sansfiltre_IdTot_wiSR_IdConc.learner ./other_inputs/Referentiel_seuils_RSDB_HF_tabase3HF_sansfiltre_IdTot_wiSR_IdConc__G.csv 97 ClassifBuzzPippip170328.learner
cd $TADARIDAC_DIR && $RSCRIPT Ta_Tc_wbuz.R $INPUT_FILE ClassifEspFrance180303.learner N 8 F T 500 0 0 ./other_inputs/SpeciesList.csv ./other_inputs/CNS_tabase3HF_France_IdConc.learner T ./other_inputs/Referentiel_seuils_ProbEspHF_.csv 500 ClassifEsp_tabase3HF_France_Cir_2019-11-26_wiSR.learner ./other_inputs/CNS_RSDB_HF_tabase3HF_sansfiltre_IdTot_wiSR_IdConc.learner ./other_inputs/Referentiel_seuils_RSDB_HF_tabase3HF_sansfiltre_IdTot_wiSR_IdConc__G.csv 98 ClassifBuzzPippip170328.learner
cd $TADARIDAC_DIR && $RSCRIPT Ta_Tc_wbuz.R $INPUT_FILE ClassifEspFrance180303.learner N 8 F T 500 0 0 ./other_inputs/SpeciesList.csv ./other_inputs/CNS_tabase3HF_France_IdConc.learner T ./other_inputs/Referentiel_seuils_ProbEspHF_.csv 500 ClassifEsp_tabase3HF_France_Cir_2019-11-26_wiSR.learner ./other_inputs/CNS_RSDB_HF_tabase3HF_sansfiltre_IdTot_wiSR_IdConc.learner ./other_inputs/Referentiel_seuils_RSDB_HF_tabase3HF_sansfiltre_IdTot_wiSR_IdConc__G.csv 99 ClassifBuzzPippip170328.learner
cd $TADARIDAC_DIR && $RSCRIPT Ta_Tc_wbuz.R $INPUT_FILE ClassifEspFrance180303.learner N 8 F T 500 0 0 ./other_inputs/SpeciesList.csv ./other_inputs/CNS_tabase3HF_France_IdConc.learner T ./other_inputs/Referentiel_seuils_ProbEspHF_.csv 500 ClassifEsp_tabase3HF_France_Cir_2019-11-26_wiSR.learner ./other_inputs/CNS_RSDB_HF_tabase3HF_sansfiltre_IdTot_wiSR_IdConc.learner ./other_inputs/Referentiel_seuils_RSDB_HF_tabase3HF_sansfiltre_IdTot_wiSR_IdConc__G.csv 100 ClassifBuzzPippip170328.learner
cd $TADARIDAC_DIR && $RSCRIPT Ta_Tc_wbuz.R $INPUT_FILE ClassifEspFrance180303.learner N 8 F T 500 0 0 ./other_inputs/SpeciesList.csv ./other_inputs/CNS_tabase3HF_France_IdConc.learner T ./other_inputs/Referentiel_seuils_ProbEspHF_.csv 500 ClassifEsp_tabase3HF_France_Cir_2019-11-26_wiSR.learner ./other_inputs/CNS_RSDB_HF_tabase3HF_sansfiltre_IdTot_wiSR_IdConc.learner ./other_inputs/Referentiel_seuils_RSDB_HF_tabase3HF_sansfiltre_IdTot_wiSR_IdConc__G.csv 101 ClassifBuzzPippip170328.learner
cd $TADARIDAC_DIR && $RSCRIPT Ta_Tc_wbuz.R $INPUT_FILE ClassifEspFrance180303.learner N 8 F T 500 0 0 ./other_inputs/SpeciesList.csv ./other_inputs/CNS_tabase3HF_France_IdConc.learner T ./other_inputs/Referentiel_seuils_ProbEspHF_.csv 500 ClassifEsp_tabase3HF_France_Cir_2019-11-26_wiSR.learner ./other_inputs/CNS_RSDB_HF_tabase3HF_sansfiltre_IdTot_wiSR_IdConc.learner ./other_inputs/Referentiel_seuils_RSDB_HF_tabase3HF_sansfiltre_IdTot_wiSR_IdConc__G.csv 102 ClassifBuzzPippip170328.learner
cd $TADARIDAC_DIR && $RSCRIPT Ta_Tc_wbuz.R $INPUT_FILE ClassifEspFrance180303.learner N 8 F T 500 0 0 ./other_inputs/SpeciesList.csv ./other_inputs/CNS_tabase3HF_France_IdConc.learner T ./other_inputs/Referentiel_seuils_ProbEspHF_.csv 500 ClassifEsp_tabase3HF_France_Cir_2019-11-26_wiSR.learner ./other_inputs/CNS_RSDB_HF_tabase3HF_sansfiltre_IdTot_wiSR_IdConc.learner ./other_inputs/Referentiel_seuils_RSDB_HF_tabase3HF_sansfiltre_IdTot_wiSR_IdConc__G.csv 103 ClassifBuzzPippip170328.learner
cd $TADARIDAC_DIR && $RSCRIPT Ta_Tc_wbuz.R $INPUT_FILE ClassifEspFrance180303.learner N 8 F T 500 0 0 ./other_inputs/SpeciesList.csv ./other_inputs/CNS_tabase3HF_France_IdConc.learner T ./other_inputs/Referentiel_seuils_ProbEspHF_.csv 500 ClassifEsp_tabase3HF_France_Cir_2019-11-26_wiSR.learner ./other_inputs/CNS_RSDB_HF_tabase3HF_sansfiltre_IdTot_wiSR_IdConc.learner ./other_inputs/Referentiel_seuils_RSDB_HF_tabase3HF_sansfiltre_IdTot_wiSR_IdConc__G.csv 104 ClassifBuzzPippip170328.learner
cd $TADARIDAC_DIR && $RSCRIPT Ta_Tc_wbuz.R $INPUT_FILE ClassifEspFrance180303.learner N 8 F T 500 0 0 ./other_inputs/SpeciesList.csv ./other_inputs/CNS_tabase3HF_France_IdConc.learner T ./other_inputs/Referentiel_seuils_ProbEspHF_.csv 500 ClassifEsp_tabase3HF_France_Cir_2019-11-26_wiSR.learner ./other_inputs/CNS_RSDB_HF_tabase3HF_sansfiltre_IdTot_wiSR_IdConc.learner ./other_inputs/Referentiel_seuils_RSDB_HF_tabase3HF_sansfiltre_IdTot_wiSR_IdConc__G.csv 105 ClassifBuzzPippip170328.learner
cd $TADARIDAC_DIR && $RSCRIPT Ta_Tc_wbuz.R $INPUT_FILE ClassifEspFrance180303.learner N 8 F T 500 0 0 ./other_inputs/SpeciesList.csv ./other_inputs/CNS_tabase3HF_France_IdConc.learner T ./other_inputs/Referentiel_seuils_ProbEspHF_.csv 500 ClassifEsp_tabase3HF_France_Cir_2019-11-26_wiSR.learner ./other_inputs/CNS_RSDB_HF_tabase3HF_sansfiltre_IdTot_wiSR_IdConc.learner ./other_inputs/Referentiel_seuils_RSDB_HF_tabase3HF_sansfiltre_IdTot_wiSR_IdConc__G.csv 106 ClassifBuzzPippip170328.learner
cd $TADARIDAC_DIR && $RSCRIPT Ta_Tc_wbuz.R $INPUT_FILE ClassifEspFrance180303.learner N 8 F T 500 0 0 ./other_inputs/SpeciesList.csv ./other_inputs/CNS_tabase3HF_France_IdConc.learner T ./other_inputs/Referentiel_seuils_ProbEspHF_.csv 500 ClassifEsp_tabase3HF_France_Cir_2019-11-26_wiSR.learner ./other_inputs/CNS_RSDB_HF_tabase3HF_sansfiltre_IdTot_wiSR_IdConc.learner ./other_inputs/Referentiel_seuils_RSDB_HF_tabase3HF_sansfiltre_IdTot_wiSR_IdConc__G.csv 107 ClassifBuzzPippip170328.learner
cd $TADARIDAC_DIR && $RSCRIPT Ta_Tc_wbuz.R $INPUT_FILE ClassifEspFrance180303.learner N 8 F T 500 0 0 ./other_inputs/SpeciesList.csv ./other_inputs/CNS_tabase3HF_France_IdConc.learner T ./other_inputs/Referentiel_seuils_ProbEspHF_.csv 500 ClassifEsp_tabase3HF_France_Cir_2019-11-26_wiSR.learner ./other_inputs/CNS_RSDB_HF_tabase3HF_sansfiltre_IdTot_wiSR_IdConc.learner ./other_inputs/Referentiel_seuils_RSDB_HF_tabase3HF_sansfiltre_IdTot_wiSR_IdConc__G.csv 108 ClassifBuzzPippip170328.learner
cd $TADARIDAC_DIR && $RSCRIPT Ta_Tc_wbuz.R $INPUT_FILE ClassifEspFrance180303.learner N 8 F T 500 0 0 ./other_inputs/SpeciesList.csv ./other_inputs/CNS_tabase3HF_France_IdConc.learner T ./other_inputs/Referentiel_seuils_ProbEspHF_.csv 500 ClassifEsp_tabase3HF_France_Cir_2019-11-26_wiSR.learner ./other_inputs/CNS_RSDB_HF_tabase3HF_sansfiltre_IdTot_wiSR_IdConc.learner ./other_inputs/Referentiel_seuils_RSDB_HF_tabase3HF_sansfiltre_IdTot_wiSR_IdConc__G.csv 109 ClassifBuzzPippip170328.learner
cd $TADARIDAC_DIR && $RSCRIPT Ta_Tc_wbuz.R $INPUT_FILE ClassifEspFrance180303.learner N 8 F T 500 0 0 ./other_inputs/SpeciesList.csv ./other_inputs/CNS_tabase3HF_France_IdConc.learner T ./other_inputs/Referentiel_seuils_ProbEspHF_.csv 500 ClassifEsp_tabase3HF_France_Cir_2019-11-26_wiSR.learner ./other_inputs/CNS_RSDB_HF_tabase3HF_sansfiltre_IdTot_wiSR_IdConc.learner ./other_inputs/Referentiel_seuils_RSDB_HF_tabase3HF_sansfiltre_IdTot_wiSR_IdConc__G.csv 110 ClassifBuzzPippip170328.learner
cd $TADARIDAC_DIR && $RSCRIPT Ta_Tc_wbuz.R $INPUT_FILE ClassifEspFrance180303.learner N 8 F T 500 0 0 ./other_inputs/SpeciesList.csv ./other_inputs/CNS_tabase3HF_France_IdConc.learner T ./other_inputs/Referentiel_seuils_ProbEspHF_.csv 500 ClassifEsp_tabase3HF_France_Cir_2019-11-26_wiSR.learner ./other_inputs/CNS_RSDB_HF_tabase3HF_sansfiltre_IdTot_wiSR_IdConc.learner ./other_inputs/Referentiel_seuils_RSDB_HF_tabase3HF_sansfiltre_IdTot_wiSR_IdConc__G.csv 111 ClassifBuzzPippip170328.learner
cd $TADARIDAC_DIR && $RSCRIPT Ta_Tc_wbuz.R $INPUT_FILE ClassifEspFrance180303.learner N 8 F T 500 0 0 ./other_inputs/SpeciesList.csv ./other_inputs/CNS_tabase3HF_France_IdConc.learner T ./other_inputs/Referentiel_seuils_ProbEspHF_.csv 500 ClassifEsp_tabase3HF_France_Cir_2019-11-26_wiSR.learner ./other_inputs/CNS_RSDB_HF_tabase3HF_sansfiltre_IdTot_wiSR_IdConc.learner ./other_inputs/Referentiel_seuils_RSDB_HF_tabase3HF_sansfiltre_IdTot_wiSR_IdConc__G.csv 112 ClassifBuzzPippip170328.learner
cd $TADARIDAC_DIR && $RSCRIPT Ta_Tc_wbuz.R $INPUT_FILE ClassifEspFrance180303.learner N 8 F T 500 0 0 ./other_inputs/SpeciesList.csv ./other_inputs/CNS_tabase3HF_France_IdConc.learner T ./other_inputs/Referentiel_seuils_ProbEspHF_.csv 500 ClassifEsp_tabase3HF_France_Cir_2019-11-26_wiSR.learner ./other_inputs/CNS_RSDB_HF_tabase3HF_sansfiltre_IdTot_wiSR_IdConc.learner ./other_inputs/Referentiel_seuils_RSDB_HF_tabase3HF_sansfiltre_IdTot_wiSR_IdConc__G.csv 113 ClassifBuzzPippip170328.learner
cd $TADARIDAC_DIR && $RSCRIPT Ta_Tc_wbuz.R $INPUT_FILE ClassifEspFrance180303.learner N 8 F T 500 0 0 ./other_inputs/SpeciesList.csv ./other_inputs/CNS_tabase3HF_France_IdConc.learner T ./other_inputs/Referentiel_seuils_ProbEspHF_.csv 500 ClassifEsp_tabase3HF_France_Cir_2019-11-26_wiSR.learner ./other_inputs/CNS_RSDB_HF_tabase3HF_sansfiltre_IdTot_wiSR_IdConc.learner ./other_inputs/Referentiel_seuils_RSDB_HF_tabase3HF_sansfiltre_IdTot_wiSR_IdConc__G.csv 114 ClassifBuzzPippip170328.learner
cd $TADARIDAC_DIR && $RSCRIPT Ta_Tc_wbuz.R $INPUT_FILE ClassifEspFrance180303.learner N 8 F T 500 0 0 ./other_inputs/SpeciesList.csv ./other_inputs/CNS_tabase3HF_France_IdConc.learner T ./other_inputs/Referentiel_seuils_ProbEspHF_.csv 500 ClassifEsp_tabase3HF_France_Cir_2019-11-26_wiSR.learner ./other_inputs/CNS_RSDB_HF_tabase3HF_sansfiltre_IdTot_wiSR_IdConc.learner ./other_inputs/Referentiel_seuils_RSDB_HF_tabase3HF_sansfiltre_IdTot_wiSR_IdConc__G.csv 115 ClassifBuzzPippip170328.learner
cd $TADARIDAC_DIR && $RSCRIPT Ta_Tc_wbuz.R $INPUT_FILE ClassifEspFrance180303.learner N 8 F T 500 0 0 ./other_inputs/SpeciesList.csv ./other_inputs/CNS_tabase3HF_France_IdConc.learner T ./other_inputs/Referentiel_seuils_ProbEspHF_.csv 500 ClassifEsp_tabase3HF_France_Cir_2019-11-26_wiSR.learner ./other_inputs/CNS_RSDB_HF_tabase3HF_sansfiltre_IdTot_wiSR_IdConc.learner ./other_inputs/Referentiel_seuils_RSDB_HF_tabase3HF_sansfiltre_IdTot_wiSR_IdConc__G.csv 116 ClassifBuzzPippip170328.learner
cd $TADARIDAC_DIR && $RSCRIPT Ta_Tc_wbuz.R $INPUT_FILE ClassifEspFrance180303.learner N 8 F T 500 0 0 ./other_inputs/SpeciesList.csv ./other_inputs/CNS_tabase3HF_France_IdConc.learner T ./other_inputs/Referentiel_seuils_ProbEspHF_.csv 500 ClassifEsp_tabase3HF_France_Cir_2019-11-26_wiSR.learner ./other_inputs/CNS_RSDB_HF_tabase3HF_sansfiltre_IdTot_wiSR_IdConc.learner ./other_inputs/Referentiel_seuils_RSDB_HF_tabase3HF_sansfiltre_IdTot_wiSR_IdConc__G.csv 117 ClassifBuzzPippip170328.learner
cd $TADARIDAC_DIR && $RSCRIPT Ta_Tc_wbuz.R $INPUT_FILE ClassifEspFrance180303.learner N 8 F T 500 0 0 ./other_inputs/SpeciesList.csv ./other_inputs/CNS_tabase3HF_France_IdConc.learner T ./other_inputs/Referentiel_seuils_ProbEspHF_.csv 500 ClassifEsp_tabase3HF_France_Cir_2019-11-26_wiSR.learner ./other_inputs/CNS_RSDB_HF_tabase3HF_sansfiltre_IdTot_wiSR_IdConc.learner ./other_inputs/Referentiel_seuils_RSDB_HF_tabase3HF_sansfiltre_IdTot_wiSR_IdConc__G.csv 118 ClassifBuzzPippip170328.learner
cd $TADARIDAC_DIR && $RSCRIPT Ta_Tc_wbuz.R $INPUT_FILE ClassifEspFrance180303.learner N 8 F T 500 0 0 ./other_inputs/SpeciesList.csv ./other_inputs/CNS_tabase3HF_France_IdConc.learner T ./other_inputs/Referentiel_seuils_ProbEspHF_.csv 500 ClassifEsp_tabase3HF_France_Cir_2019-11-26_wiSR.learner ./other_inputs/CNS_RSDB_HF_tabase3HF_sansfiltre_IdTot_wiSR_IdConc.learner ./other_inputs/Referentiel_seuils_RSDB_HF_tabase3HF_sansfiltre_IdTot_wiSR_IdConc__G.csv 119 ClassifBuzzPippip170328.learner
cd $TADARIDAC_DIR && $RSCRIPT Ta_Tc_wbuz.R $INPUT_FILE ClassifEspFrance180303.learner N 8 F T 500 0 0 ./other_inputs/SpeciesList.csv ./other_inputs/CNS_tabase3HF_France_IdConc.learner T ./other_inputs/Referentiel_seuils_ProbEspHF_.csv 500 ClassifEsp_tabase3HF_France_Cir_2019-11-26_wiSR.learner ./other_inputs/CNS_RSDB_HF_tabase3HF_sansfiltre_IdTot_wiSR_IdConc.learner ./other_inputs/Referentiel_seuils_RSDB_HF_tabase3HF_sansfiltre_IdTot_wiSR_IdConc__G.csv 120 ClassifBuzzPippip170328.learner
cd $TADARIDAC_DIR && $RSCRIPT Ta_Tc_wbuz.R $INPUT_FILE ClassifEspFrance180303.learner N 8 F T 500 0 0 ./other_inputs/SpeciesList.csv ./other_inputs/CNS_tabase3HF_France_IdConc.learner T ./other_inputs/Referentiel_seuils_ProbEspHF_.csv 500 ClassifEsp_tabase3HF_France_Cir_2019-11-26_wiSR.learner ./other_inputs/CNS_RSDB_HF_tabase3HF_sansfiltre_IdTot_wiSR_IdConc.learner ./other_inputs/Referentiel_seuils_RSDB_HF_tabase3HF_sansfiltre_IdTot_wiSR_IdConc__G.csv 121 ClassifBuzzPippip170328.learner
cd $TADARIDAC_DIR && $RSCRIPT Ta_Tc_wbuz.R $INPUT_FILE ClassifEspFrance180303.learner N 8 F T 500 0 0 ./other_inputs/SpeciesList.csv ./other_inputs/CNS_tabase3HF_France_IdConc.learner T ./other_inputs/Referentiel_seuils_ProbEspHF_.csv 500 ClassifEsp_tabase3HF_France_Cir_2019-11-26_wiSR.learner ./other_inputs/CNS_RSDB_HF_tabase3HF_sansfiltre_IdTot_wiSR_IdConc.learner ./other_inputs/Referentiel_seuils_RSDB_HF_tabase3HF_sansfiltre_IdTot_wiSR_IdConc__G.csv 122 ClassifBuzzPippip170328.learner
cd $TADARIDAC_DIR && $RSCRIPT Ta_Tc_wbuz.R $INPUT_FILE ClassifEspFrance180303.learner N 8 F T 500 0 0 ./other_inputs/SpeciesList.csv ./other_inputs/CNS_tabase3HF_France_IdConc.learner T ./other_inputs/Referentiel_seuils_ProbEspHF_.csv 500 ClassifEsp_tabase3HF_France_Cir_2019-11-26_wiSR.learner ./other_inputs/CNS_RSDB_HF_tabase3HF_sansfiltre_IdTot_wiSR_IdConc.learner ./other_inputs/Referentiel_seuils_RSDB_HF_tabase3HF_sansfiltre_IdTot_wiSR_IdConc__G.csv 123 ClassifBuzzPippip170328.learner
cd $TADARIDAC_DIR && $RSCRIPT Ta_Tc_wbuz.R $INPUT_FILE ClassifEspFrance180303.learner N 8 F T 500 0 0 ./other_inputs/SpeciesList.csv ./other_inputs/CNS_tabase3HF_France_IdConc.learner T ./other_inputs/Referentiel_seuils_ProbEspHF_.csv 500 ClassifEsp_tabase3HF_France_Cir_2019-11-26_wiSR.learner ./other_inputs/CNS_RSDB_HF_tabase3HF_sansfiltre_IdTot_wiSR_IdConc.learner ./other_inputs/Referentiel_seuils_RSDB_HF_tabase3HF_sansfiltre_IdTot_wiSR_IdConc__G.csv 124 ClassifBuzzPippip170328.learner
cd $TADARIDAC_DIR && $RSCRIPT Ta_Tc_wbuz.R $INPUT_FILE ClassifEspFrance180303.learner N 8 F T 500 0 0 ./other_inputs/SpeciesList.csv ./other_inputs/CNS_tabase3HF_France_IdConc.learner T ./other_inputs/Referentiel_seuils_ProbEspHF_.csv 500 ClassifEsp_tabase3HF_France_Cir_2019-11-26_wiSR.learner ./other_inputs/CNS_RSDB_HF_tabase3HF_sansfiltre_IdTot_wiSR_IdConc.learner ./other_inputs/Referentiel_seuils_RSDB_HF_tabase3HF_sansfiltre_IdTot_wiSR_IdConc__G.csv 125 ClassifBuzzPippip170328.learner
cd $TADARIDAC_DIR && $RSCRIPT Ta_Tc_wbuz.R $INPUT_FILE ClassifEspFrance180303.learner N 8 F T 500 0 0 ./other_inputs/SpeciesList.csv ./other_inputs/CNS_tabase3HF_France_IdConc.learner T ./other_inputs/Referentiel_seuils_ProbEspHF_.csv 500 ClassifEsp_tabase3HF_France_Cir_2019-11-26_wiSR.learner ./other_inputs/CNS_RSDB_HF_tabase3HF_sansfiltre_IdTot_wiSR_IdConc.learner ./other_inputs/Referentiel_seuils_RSDB_HF_tabase3HF_sansfiltre_IdTot_wiSR_IdConc__G.csv 126 ClassifBuzzPippip170328.learner
cd $TADARIDAC_DIR && $RSCRIPT Ta_Tc_wbuz.R $INPUT_FILE ClassifEspFrance180303.learner N 8 F T 500 0 0 ./other_inputs/SpeciesList.csv ./other_inputs/CNS_tabase3HF_France_IdConc.learner T ./other_inputs/Referentiel_seuils_ProbEspHF_.csv 500 ClassifEsp_tabase3HF_France_Cir_2019-11-26_wiSR.learner ./other_inputs/CNS_RSDB_HF_tabase3HF_sansfiltre_IdTot_wiSR_IdConc.learner ./other_inputs/Referentiel_seuils_RSDB_HF_tabase3HF_sansfiltre_IdTot_wiSR_IdConc__G.csv 127 ClassifBuzzPippip170328.learner
cd $TADARIDAC_DIR && $RSCRIPT Ta_Tc_wbuz.R $INPUT_FILE ClassifEspFrance180303.learner N 8 F T 500 0 0 ./other_inputs/SpeciesList.csv ./other_inputs/CNS_tabase3HF_France_IdConc.learner T ./other_inputs/Referentiel_seuils_ProbEspHF_.csv 500 ClassifEsp_tabase3HF_France_Cir_2019-11-26_wiSR.learner ./other_inputs/CNS_RSDB_HF_tabase3HF_sansfiltre_IdTot_wiSR_IdConc.learner ./other_inputs/Referentiel_seuils_RSDB_HF_tabase3HF_sansfiltre_IdTot_wiSR_IdConc__G.csv 128 ClassifBuzzPippip170328.learner
cd $TADARIDAC_DIR && $RSCRIPT Ta_Tc_wbuz.R $INPUT_FILE ClassifEspFrance180303.learner N 8 F T 500 0 0 ./other_inputs/SpeciesList.csv ./other_inputs/CNS_tabase3HF_France_IdConc.learner T ./other_inputs/Referentiel_seuils_ProbEspHF_.csv 500 ClassifEsp_tabase3HF_France_Cir_2019-11-26_wiSR.learner ./other_inputs/CNS_RSDB_HF_tabase3HF_sansfiltre_IdTot_wiSR_IdConc.learner ./other_inputs/Referentiel_seuils_RSDB_HF_tabase3HF_sansfiltre_IdTot_wiSR_IdConc__G.csv 129 ClassifBuzzPippip170328.learner
cd $TADARIDAC_DIR && $RSCRIPT Ta_Tc_wbuz.R $INPUT_FILE ClassifEspFrance180303.learner N 8 F T 500 0 0 ./other_inputs/SpeciesList.csv ./other_inputs/CNS_tabase3HF_France_IdConc.learner T ./other_inputs/Referentiel_seuils_ProbEspHF_.csv 500 ClassifEsp_tabase3HF_France_Cir_2019-11-26_wiSR.learner ./other_inputs/CNS_RSDB_HF_tabase3HF_sansfiltre_IdTot_wiSR_IdConc.learner ./other_inputs/Referentiel_seuils_RSDB_HF_tabase3HF_sansfiltre_IdTot_wiSR_IdConc__G.csv 130 ClassifBuzzPippip170328.learner
cd $TADARIDAC_DIR && $RSCRIPT Ta_Tc_wbuz.R $INPUT_FILE ClassifEspFrance180303.learner N 8 F T 500 0 0 ./other_inputs/SpeciesList.csv ./other_inputs/CNS_tabase3HF_France_IdConc.learner T ./other_inputs/Referentiel_seuils_ProbEspHF_.csv 500 ClassifEsp_tabase3HF_France_Cir_2019-11-26_wiSR.learner ./other_inputs/CNS_RSDB_HF_tabase3HF_sansfiltre_IdTot_wiSR_IdConc.learner ./other_inputs/Referentiel_seuils_RSDB_HF_tabase3HF_sansfiltre_IdTot_wiSR_IdConc__G.csv 131 ClassifBuzzPippip170328.learner
cd $TADARIDAC_DIR && $RSCRIPT Ta_Tc_wbuz.R $INPUT_FILE ClassifEspFrance180303.learner N 8 F T 500 0 0 ./other_inputs/SpeciesList.csv ./other_inputs/CNS_tabase3HF_France_IdConc.learner T ./other_inputs/Referentiel_seuils_ProbEspHF_.csv 500 ClassifEsp_tabase3HF_France_Cir_2019-11-26_wiSR.learner ./other_inputs/CNS_RSDB_HF_tabase3HF_sansfiltre_IdTot_wiSR_IdConc.learner ./other_inputs/Referentiel_seuils_RSDB_HF_tabase3HF_sansfiltre_IdTot_wiSR_IdConc__G.csv 132 ClassifBuzzPippip170328.learner
cd $TADARIDAC_DIR && $RSCRIPT Ta_Tc_wbuz.R $INPUT_FILE ClassifEspFrance180303.learner N 8 F T 500 0 0 ./other_inputs/SpeciesList.csv ./other_inputs/CNS_tabase3HF_France_IdConc.learner T ./other_inputs/Referentiel_seuils_ProbEspHF_.csv 500 ClassifEsp_tabase3HF_France_Cir_2019-11-26_wiSR.learner ./other_inputs/CNS_RSDB_HF_tabase3HF_sansfiltre_IdTot_wiSR_IdConc.learner ./other_inputs/Referentiel_seuils_RSDB_HF_tabase3HF_sansfiltre_IdTot_wiSR_IdConc__G.csv 133 ClassifBuzzPippip170328.learner
cd $TADARIDAC_DIR && $RSCRIPT Ta_Tc_wbuz.R $INPUT_FILE ClassifEspFrance180303.learner N 8 F T 500 0 0 ./other_inputs/SpeciesList.csv ./other_inputs/CNS_tabase3HF_France_IdConc.learner T ./other_inputs/Referentiel_seuils_ProbEspHF_.csv 500 ClassifEsp_tabase3HF_France_Cir_2019-11-26_wiSR.learner ./other_inputs/CNS_RSDB_HF_tabase3HF_sansfiltre_IdTot_wiSR_IdConc.learner ./other_inputs/Referentiel_seuils_RSDB_HF_tabase3HF_sansfiltre_IdTot_wiSR_IdConc__G.csv 134 ClassifBuzzPippip170328.learner
cd $TADARIDAC_DIR && $RSCRIPT Ta_Tc_wbuz.R $INPUT_FILE ClassifEspFrance180303.learner N 8 F T 500 0 0 ./other_inputs/SpeciesList.csv ./other_inputs/CNS_tabase3HF_France_IdConc.learner T ./other_inputs/Referentiel_seuils_ProbEspHF_.csv 500 ClassifEsp_tabase3HF_France_Cir_2019-11-26_wiSR.learner ./other_inputs/CNS_RSDB_HF_tabase3HF_sansfiltre_IdTot_wiSR_IdConc.learner ./other_inputs/Referentiel_seuils_RSDB_HF_tabase3HF_sansfiltre_IdTot_wiSR_IdConc__G.csv 135 ClassifBuzzPippip170328.learner
cd $TADARIDAC_DIR && $RSCRIPT Ta_Tc_wbuz.R $INPUT_FILE ClassifEspFrance180303.learner N 8 F T 500 0 0 ./other_inputs/SpeciesList.csv ./other_inputs/CNS_tabase3HF_France_IdConc.learner T ./other_inputs/Referentiel_seuils_ProbEspHF_.csv 500 ClassifEsp_tabase3HF_France_Cir_2019-11-26_wiSR.learner ./other_inputs/CNS_RSDB_HF_tabase3HF_sansfiltre_IdTot_wiSR_IdConc.learner ./other_inputs/Referentiel_seuils_RSDB_HF_tabase3HF_sansfiltre_IdTot_wiSR_IdConc__G.csv 136 ClassifBuzzPippip170328.learner
cd $TADARIDAC_DIR && $RSCRIPT Ta_Tc_wbuz.R $INPUT_FILE ClassifEspFrance180303.learner N 8 F T 500 0 0 ./other_inputs/SpeciesList.csv ./other_inputs/CNS_tabase3HF_France_IdConc.learner T ./other_inputs/Referentiel_seuils_ProbEspHF_.csv 500 ClassifEsp_tabase3HF_France_Cir_2019-11-26_wiSR.learner ./other_inputs/CNS_RSDB_HF_tabase3HF_sansfiltre_IdTot_wiSR_IdConc.learner ./other_inputs/Referentiel_seuils_RSDB_HF_tabase3HF_sansfiltre_IdTot_wiSR_IdConc__G.csv 137 ClassifBuzzPippip170328.learner
cd $TADARIDAC_DIR && $RSCRIPT Ta_Tc_wbuz.R $INPUT_FILE ClassifEspFrance180303.learner N 8 F T 500 0 0 ./other_inputs/SpeciesList.csv ./other_inputs/CNS_tabase3HF_France_IdConc.learner T ./other_inputs/Referentiel_seuils_ProbEspHF_.csv 500 ClassifEsp_tabase3HF_France_Cir_2019-11-26_wiSR.learner ./other_inputs/CNS_RSDB_HF_tabase3HF_sansfiltre_IdTot_wiSR_IdConc.learner ./other_inputs/Referentiel_seuils_RSDB_HF_tabase3HF_sansfiltre_IdTot_wiSR_IdConc__G.csv 138 ClassifBuzzPippip170328.learner
cd $TADARIDAC_DIR && $RSCRIPT Ta_Tc_wbuz.R $INPUT_FILE ClassifEspFrance180303.learner N 8 F T 500 0 0 ./other_inputs/SpeciesList.csv ./other_inputs/CNS_tabase3HF_France_IdConc.learner T ./other_inputs/Referentiel_seuils_ProbEspHF_.csv 500 ClassifEsp_tabase3HF_France_Cir_2019-11-26_wiSR.learner ./other_inputs/CNS_RSDB_HF_tabase3HF_sansfiltre_IdTot_wiSR_IdConc.learner ./other_inputs/Referentiel_seuils_RSDB_HF_tabase3HF_sansfiltre_IdTot_wiSR_IdConc__G.csv 139 ClassifBuzzPippip170328.learner
cd $TADARIDAC_DIR && $RSCRIPT Ta_Tc_wbuz.R $INPUT_FILE ClassifEspFrance180303.learner N 8 F T 500 0 0 ./other_inputs/SpeciesList.csv ./other_inputs/CNS_tabase3HF_France_IdConc.learner T ./other_inputs/Referentiel_seuils_ProbEspHF_.csv 500 ClassifEsp_tabase3HF_France_Cir_2019-11-26_wiSR.learner ./other_inputs/CNS_RSDB_HF_tabase3HF_sansfiltre_IdTot_wiSR_IdConc.learner ./other_inputs/Referentiel_seuils_RSDB_HF_tabase3HF_sansfiltre_IdTot_wiSR_IdConc__G.csv 140 ClassifBuzzPippip170328.learner
cd $TADARIDAC_DIR && $RSCRIPT Ta_Tc_wbuz.R $INPUT_FILE ClassifEspFrance180303.learner N 8 F T 500 0 0 ./other_inputs/SpeciesList.csv ./other_inputs/CNS_tabase3HF_France_IdConc.learner T ./other_inputs/Referentiel_seuils_ProbEspHF_.csv 500 ClassifEsp_tabase3HF_France_Cir_2019-11-26_wiSR.learner ./other_inputs/CNS_RSDB_HF_tabase3HF_sansfiltre_IdTot_wiSR_IdConc.learner ./other_inputs/Referentiel_seuils_RSDB_HF_tabase3HF_sansfiltre_IdTot_wiSR_IdConc__G.csv 141 ClassifBuzzPippip170328.learner
cd $TADARIDAC_DIR && $RSCRIPT Ta_Tc_wbuz.R $INPUT_FILE ClassifEspFrance180303.learner N 8 F T 500 0 0 ./other_inputs/SpeciesList.csv ./other_inputs/CNS_tabase3HF_France_IdConc.learner T ./other_inputs/Referentiel_seuils_ProbEspHF_.csv 500 ClassifEsp_tabase3HF_France_Cir_2019-11-26_wiSR.learner ./other_inputs/CNS_RSDB_HF_tabase3HF_sansfiltre_IdTot_wiSR_IdConc.learner ./other_inputs/Referentiel_seuils_RSDB_HF_tabase3HF_sansfiltre_IdTot_wiSR_IdConc__G.csv 142 ClassifBuzzPippip170328.learner
cd $TADARIDAC_DIR && $RSCRIPT Ta_Tc_wbuz.R $INPUT_FILE ClassifEspFrance180303.learner N 8 F T 500 0 0 ./other_inputs/SpeciesList.csv ./other_inputs/CNS_tabase3HF_France_IdConc.learner T ./other_inputs/Referentiel_seuils_ProbEspHF_.csv 500 ClassifEsp_tabase3HF_France_Cir_2019-11-26_wiSR.learner ./other_inputs/CNS_RSDB_HF_tabase3HF_sansfiltre_IdTot_wiSR_IdConc.learner ./other_inputs/Referentiel_seuils_RSDB_HF_tabase3HF_sansfiltre_IdTot_wiSR_IdConc__G.csv 143 ClassifBuzzPippip170328.learner
cd $TADARIDAC_DIR && $RSCRIPT Ta_Tc_wbuz.R $INPUT_FILE ClassifEspFrance180303.learner N 8 F T 500 0 0 ./other_inputs/SpeciesList.csv ./other_inputs/CNS_tabase3HF_France_IdConc.learner T ./other_inputs/Referentiel_seuils_ProbEspHF_.csv 500 ClassifEsp_tabase3HF_France_Cir_2019-11-26_wiSR.learner ./other_inputs/CNS_RSDB_HF_tabase3HF_sansfiltre_IdTot_wiSR_IdConc.learner ./other_inputs/Referentiel_seuils_RSDB_HF_tabase3HF_sansfiltre_IdTot_wiSR_IdConc__G.csv 144 ClassifBuzzPippip170328.learner
cd $TADARIDAC_DIR && $RSCRIPT Ta_Tc_wbuz.R $INPUT_FILE ClassifEspFrance180303.learner N 8 F T 500 0 0 ./other_inputs/SpeciesList.csv ./other_inputs/CNS_tabase3HF_France_IdConc.learner T ./other_inputs/Referentiel_seuils_ProbEspHF_.csv 500 ClassifEsp_tabase3HF_France_Cir_2019-11-26_wiSR.learner ./other_inputs/CNS_RSDB_HF_tabase3HF_sansfiltre_IdTot_wiSR_IdConc.learner ./other_inputs/Referentiel_seuils_RSDB_HF_tabase3HF_sansfiltre_IdTot_wiSR_IdConc__G.csv 145 ClassifBuzzPippip170328.learner
cd $TADARIDAC_DIR && $RSCRIPT Ta_Tc_wbuz.R $INPUT_FILE ClassifEspFrance180303.learner N 8 F T 500 0 0 ./other_inputs/SpeciesList.csv ./other_inputs/CNS_tabase3HF_France_IdConc.learner T ./other_inputs/Referentiel_seuils_ProbEspHF_.csv 500 ClassifEsp_tabase3HF_France_Cir_2019-11-26_wiSR.learner ./other_inputs/CNS_RSDB_HF_tabase3HF_sansfiltre_IdTot_wiSR_IdConc.learner ./other_inputs/Referentiel_seuils_RSDB_HF_tabase3HF_sansfiltre_IdTot_wiSR_IdConc__G.csv 146 ClassifBuzzPippip170328.learner
cd $TADARIDAC_DIR && $RSCRIPT Ta_Tc_wbuz.R $INPUT_FILE ClassifEspFrance180303.learner N 8 F T 500 0 0 ./other_inputs/SpeciesList.csv ./other_inputs/CNS_tabase3HF_France_IdConc.learner T ./other_inputs/Referentiel_seuils_ProbEspHF_.csv 500 ClassifEsp_tabase3HF_France_Cir_2019-11-26_wiSR.learner ./other_inputs/CNS_RSDB_HF_tabase3HF_sansfiltre_IdTot_wiSR_IdConc.learner ./other_inputs/Referentiel_seuils_RSDB_HF_tabase3HF_sansfiltre_IdTot_wiSR_IdConc__G.csv 147 ClassifBuzzPippip170328.learner
cd $TADARIDAC_DIR && $RSCRIPT Ta_Tc_wbuz.R $INPUT_FILE ClassifEspFrance180303.learner N 8 F T 500 0 0 ./other_inputs/SpeciesList.csv ./other_inputs/CNS_tabase3HF_France_IdConc.learner T ./other_inputs/Referentiel_seuils_ProbEspHF_.csv 500 ClassifEsp_tabase3HF_France_Cir_2019-11-26_wiSR.learner ./other_inputs/CNS_RSDB_HF_tabase3HF_sansfiltre_IdTot_wiSR_IdConc.learner ./other_inputs/Referentiel_seuils_RSDB_HF_tabase3HF_sansfiltre_IdTot_wiSR_IdConc__G.csv 148 ClassifBuzzPippip170328.learner
cd $TADARIDAC_DIR && $RSCRIPT Ta_Tc_wbuz.R $INPUT_FILE ClassifEspFrance180303.learner N 8 F T 500 0 0 ./other_inputs/SpeciesList.csv ./other_inputs/CNS_tabase3HF_France_IdConc.learner T ./other_inputs/Referentiel_seuils_ProbEspHF_.csv 500 ClassifEsp_tabase3HF_France_Cir_2019-11-26_wiSR.learner ./other_inputs/CNS_RSDB_HF_tabase3HF_sansfiltre_IdTot_wiSR_IdConc.learner ./other_inputs/Referentiel_seuils_RSDB_HF_tabase3HF_sansfiltre_IdTot_wiSR_IdConc__G.csv 149 ClassifBuzzPippip170328.learner
cd $TADARIDAC_DIR && $RSCRIPT Ta_Tc_wbuz.R $INPUT_FILE ClassifEspFrance180303.learner N 8 F T 500 0 0 ./other_inputs/SpeciesList.csv ./other_inputs/CNS_tabase3HF_France_IdConc.learner T ./other_inputs/Referentiel_seuils_ProbEspHF_.csv 500 ClassifEsp_tabase3HF_France_Cir_2019-11-26_wiSR.learner ./other_inputs/CNS_RSDB_HF_tabase3HF_sansfiltre_IdTot_wiSR_IdConc.learner ./other_inputs/Referentiel_seuils_RSDB_HF_tabase3HF_sansfiltre_IdTot_wiSR_IdConc__G.csv 150 ClassifBuzzPippip170328.learner
cd $TADARIDAC_DIR && $RSCRIPT Ta_Tc_wbuz.R $INPUT_FILE ClassifEspFrance180303.learner N 8 F T 500 0 0 ./other_inputs/SpeciesList.csv ./other_inputs/CNS_tabase3HF_France_IdConc.learner T ./other_inputs/Referentiel_seuils_ProbEspHF_.csv 500 ClassifEsp_tabase3HF_France_Cir_2019-11-26_wiSR.learner ./other_inputs/CNS_RSDB_HF_tabase3HF_sansfiltre_IdTot_wiSR_IdConc.learner ./other_inputs/Referentiel_seuils_RSDB_HF_tabase3HF_sansfiltre_IdTot_wiSR_IdConc__G.csv 151 ClassifBuzzPippip170328.learner
cd $TADARIDAC_DIR && $RSCRIPT Ta_Tc_wbuz.R $INPUT_FILE ClassifEspFrance180303.learner N 8 F T 500 0 0 ./other_inputs/SpeciesList.csv ./other_inputs/CNS_tabase3HF_France_IdConc.learner T ./other_inputs/Referentiel_seuils_ProbEspHF_.csv 500 ClassifEsp_tabase3HF_France_Cir_2019-11-26_wiSR.learner ./other_inputs/CNS_RSDB_HF_tabase3HF_sansfiltre_IdTot_wiSR_IdConc.learner ./other_inputs/Referentiel_seuils_RSDB_HF_tabase3HF_sansfiltre_IdTot_wiSR_IdConc__G.csv 152 ClassifBuzzPippip170328.learner
cd $TADARIDAC_DIR && $RSCRIPT Ta_Tc_wbuz.R $INPUT_FILE ClassifEspFrance180303.learner N 8 F T 500 0 0 ./other_inputs/SpeciesList.csv ./other_inputs/CNS_tabase3HF_France_IdConc.learner T ./other_inputs/Referentiel_seuils_ProbEspHF_.csv 500 ClassifEsp_tabase3HF_France_Cir_2019-11-26_wiSR.learner ./other_inputs/CNS_RSDB_HF_tabase3HF_sansfiltre_IdTot_wiSR_IdConc.learner ./other_inputs/Referentiel_seuils_RSDB_HF_tabase3HF_sansfiltre_IdTot_wiSR_IdConc__G.csv 153 ClassifBuzzPippip170328.learner
cd $TADARIDAC_DIR && $RSCRIPT Ta_Tc_wbuz.R $INPUT_FILE ClassifEspFrance180303.learner N 8 F T 500 0 0 ./other_inputs/SpeciesList.csv ./other_inputs/CNS_tabase3HF_France_IdConc.learner T ./other_inputs/Referentiel_seuils_ProbEspHF_.csv 500 ClassifEsp_tabase3HF_France_Cir_2019-11-26_wiSR.learner ./other_inputs/CNS_RSDB_HF_tabase3HF_sansfiltre_IdTot_wiSR_IdConc.learner ./other_inputs/Referentiel_seuils_RSDB_HF_tabase3HF_sansfiltre_IdTot_wiSR_IdConc__G.csv 154 ClassifBuzzPippip170328.learner
cd $TADARIDAC_DIR && $RSCRIPT Ta_Tc_wbuz.R $INPUT_FILE ClassifEspFrance180303.learner N 8 F T 500 0 0 ./other_inputs/SpeciesList.csv ./other_inputs/CNS_tabase3HF_France_IdConc.learner T ./other_inputs/Referentiel_seuils_ProbEspHF_.csv 500 ClassifEsp_tabase3HF_France_Cir_2019-11-26_wiSR.learner ./other_inputs/CNS_RSDB_HF_tabase3HF_sansfiltre_IdTot_wiSR_IdConc.learner ./other_inputs/Referentiel_seuils_RSDB_HF_tabase3HF_sansfiltre_IdTot_wiSR_IdConc__G.csv 155 ClassifBuzzPippip170328.learner
cd $TADARIDAC_DIR && $RSCRIPT Ta_Tc_wbuz.R $INPUT_FILE ClassifEspFrance180303.learner N 8 F T 500 0 0 ./other_inputs/SpeciesList.csv ./other_inputs/CNS_tabase3HF_France_IdConc.learner T ./other_inputs/Referentiel_seuils_ProbEspHF_.csv 500 ClassifEsp_tabase3HF_France_Cir_2019-11-26_wiSR.learner ./other_inputs/CNS_RSDB_HF_tabase3HF_sansfiltre_IdTot_wiSR_IdConc.learner ./other_inputs/Referentiel_seuils_RSDB_HF_tabase3HF_sansfiltre_IdTot_wiSR_IdConc__G.csv 156 ClassifBuzzPippip170328.learner
cd $TADARIDAC_DIR && $RSCRIPT Ta_Tc_wbuz.R $INPUT_FILE ClassifEspFrance180303.learner N 8 F T 500 0 0 ./other_inputs/SpeciesList.csv ./other_inputs/CNS_tabase3HF_France_IdConc.learner T ./other_inputs/Referentiel_seuils_ProbEspHF_.csv 500 ClassifEsp_tabase3HF_France_Cir_2019-11-26_wiSR.learner ./other_inputs/CNS_RSDB_HF_tabase3HF_sansfiltre_IdTot_wiSR_IdConc.learner ./other_inputs/Referentiel_seuils_RSDB_HF_tabase3HF_sansfiltre_IdTot_wiSR_IdConc__G.csv 157 ClassifBuzzPippip170328.learner
cd $TADARIDAC_DIR && $RSCRIPT Ta_Tc_wbuz.R $INPUT_FILE ClassifEspFrance180303.learner N 8 F T 500 0 0 ./other_inputs/SpeciesList.csv ./other_inputs/CNS_tabase3HF_France_IdConc.learner T ./other_inputs/Referentiel_seuils_ProbEspHF_.csv 500 ClassifEsp_tabase3HF_France_Cir_2019-11-26_wiSR.learner ./other_inputs/CNS_RSDB_HF_tabase3HF_sansfiltre_IdTot_wiSR_IdConc.learner ./other_inputs/Referentiel_seuils_RSDB_HF_tabase3HF_sansfiltre_IdTot_wiSR_IdConc__G.csv 158 ClassifBuzzPippip170328.learner
cd $TADARIDAC_DIR && $RSCRIPT Ta_Tc_wbuz.R $INPUT_FILE ClassifEspFrance180303.learner N 8 F T 500 0 0 ./other_inputs/SpeciesList.csv ./other_inputs/CNS_tabase3HF_France_IdConc.learner T ./other_inputs/Referentiel_seuils_ProbEspHF_.csv 500 ClassifEsp_tabase3HF_France_Cir_2019-11-26_wiSR.learner ./other_inputs/CNS_RSDB_HF_tabase3HF_sansfiltre_IdTot_wiSR_IdConc.learner ./other_inputs/Referentiel_seuils_RSDB_HF_tabase3HF_sansfiltre_IdTot_wiSR_IdConc__G.csv 159 ClassifBuzzPippip170328.learner
cd $TADARIDAC_DIR && $RSCRIPT Ta_Tc_wbuz.R $INPUT_FILE ClassifEspFrance180303.learner N 8 F T 500 0 0 ./other_inputs/SpeciesList.csv ./other_inputs/CNS_tabase3HF_France_IdConc.learner T ./other_inputs/Referentiel_seuils_ProbEspHF_.csv 500 ClassifEsp_tabase3HF_France_Cir_2019-11-26_wiSR.learner ./other_inputs/CNS_RSDB_HF_tabase3HF_sansfiltre_IdTot_wiSR_IdConc.learner ./other_inputs/Referentiel_seuils_RSDB_HF_tabase3HF_sansfiltre_IdTot_wiSR_IdConc__G.csv 160 ClassifBuzzPippip170328.learner

cd $TADARIDAC_DIR && $RSCRIPT ContextualClassif.R $INPUT_FILE ./other_inputs/SpeciesList.csv ./other_inputs/ClassifEspC3_2019-03-25.learner f_CombineProbas.R f_Rescale_Probas.r ./other_inputs/Referentiel_seuils_ProbEspC3_2019-03-25_G7__D_G.csv ./other_inputs/Referentiel_seuils_RSDB_HF_tabase3HF_sansfiltre_IdTot_wiSR_IdConc__G.csv