#! /bin/sh

if [ -z "$RSCRIPT" ]
then
    RSCRIPT=Rscript
fi

if [ -z "$TADARIDAC_DIR" ]
then
    TADARIDAC_DIR=$VIGIECHIRO_DIR/Tadarida-C/tadaridaC_src
fi
if [ -z "$TADARIDAC_LEARNER_NAME" ]
then
    TADARIDAC_LEARNER_NAME=ClassifEspFrance180303.learner
fi
TADARIDAC_LEARNER_PATH=$TADARIDAC_DIR/$TADARIDAC_LEARNER_NAME

if ( [ "$#" -eq 0 ] )
then
    echo 'usage: tadaridaC <directory>'
    exit 1
else
    INPUT_FILE=`readlink -f $1`
    if ( [ "$?" -ne 0 ] )
    then
        echo "$1 is not a valid file"
        exit 1
    fi
fi


# Finally start tadaridaC R script
cd $TADARIDAC_DIR && $RSCRIPT Ta_Tc.R $INPUT_FILE ClassifEspFrance180303.learner N 8 F T 500 0 0 ./other_inputs/SpeciesList.csv ./other_inputs/CNS_tabase3HF_France_IdConc.learner T ./other_inputs/Referentiel_seuils_ProbEspHF_.csv 1000 1
cd $TADARIDAC_DIR && $RSCRIPT Ta_Tc.R $INPUT_FILE ClassifEspFrance180303.learner N 8 F T 500 0 0 ./other_inputs/SpeciesList.csv ./other_inputs/CNS_tabase3HF_France_IdConc.learner T ./other_inputs/Referentiel_seuils_ProbEspHF_.csv 1000 2
cd $TADARIDAC_DIR && $RSCRIPT Ta_Tc.R $INPUT_FILE ClassifEspFrance180303.learner N 8 F T 500 0 0 ./other_inputs/SpeciesList.csv ./other_inputs/CNS_tabase3HF_France_IdConc.learner T ./other_inputs/Referentiel_seuils_ProbEspHF_.csv 1000 3
cd $TADARIDAC_DIR && $RSCRIPT Ta_Tc.R $INPUT_FILE ClassifEspFrance180303.learner N 8 F T 500 0 0 ./other_inputs/SpeciesList.csv ./other_inputs/CNS_tabase3HF_France_IdConc.learner T ./other_inputs/Referentiel_seuils_ProbEspHF_.csv 1000 4
cd $TADARIDAC_DIR && $RSCRIPT Ta_Tc.R $INPUT_FILE ClassifEspFrance180303.learner N 8 F T 500 0 0 ./other_inputs/SpeciesList.csv ./other_inputs/CNS_tabase3HF_France_IdConc.learner T ./other_inputs/Referentiel_seuils_ProbEspHF_.csv 1000 5
cd $TADARIDAC_DIR && $RSCRIPT Ta_Tc.R $INPUT_FILE ClassifEspFrance180303.learner N 8 F T 500 0 0 ./other_inputs/SpeciesList.csv ./other_inputs/CNS_tabase3HF_France_IdConc.learner T ./other_inputs/Referentiel_seuils_ProbEspHF_.csv 1000 6
cd $TADARIDAC_DIR && $RSCRIPT Ta_Tc.R $INPUT_FILE ClassifEspFrance180303.learner N 8 F T 500 0 0 ./other_inputs/SpeciesList.csv ./other_inputs/CNS_tabase3HF_France_IdConc.learner T ./other_inputs/Referentiel_seuils_ProbEspHF_.csv 1000 7
cd $TADARIDAC_DIR && $RSCRIPT Ta_Tc.R $INPUT_FILE ClassifEspFrance180303.learner N 8 F T 500 0 0 ./other_inputs/SpeciesList.csv ./other_inputs/CNS_tabase3HF_France_IdConc.learner T ./other_inputs/Referentiel_seuils_ProbEspHF_.csv 1000 8
cd $TADARIDAC_DIR && $RSCRIPT Ta_Tc.R $INPUT_FILE ClassifEspFrance180303.learner N 8 F T 500 0 0 ./other_inputs/SpeciesList.csv ./other_inputs/CNS_tabase3HF_France_IdConc.learner T ./other_inputs/Referentiel_seuils_ProbEspHF_.csv 1000 9
cd $TADARIDAC_DIR && $RSCRIPT Ta_Tc.R $INPUT_FILE ClassifEspFrance180303.learner N 8 F T 500 0 0 ./other_inputs/SpeciesList.csv ./other_inputs/CNS_tabase3HF_France_IdConc.learner T ./other_inputs/Referentiel_seuils_ProbEspHF_.csv 1000 10
cd $TADARIDAC_DIR && $RSCRIPT Ta_Tc.R $INPUT_FILE ClassifEspFrance180303.learner N 8 F T 500 0 0 ./other_inputs/SpeciesList.csv ./other_inputs/CNS_tabase3HF_France_IdConc.learner T ./other_inputs/Referentiel_seuils_ProbEspHF_.csv 1000 11
cd $TADARIDAC_DIR && $RSCRIPT Ta_Tc.R $INPUT_FILE ClassifEspFrance180303.learner N 8 F T 500 0 0 ./other_inputs/SpeciesList.csv ./other_inputs/CNS_tabase3HF_France_IdConc.learner T ./other_inputs/Referentiel_seuils_ProbEspHF_.csv 1000 12
cd $TADARIDAC_DIR && $RSCRIPT Ta_Tc.R $INPUT_FILE ClassifEspFrance180303.learner N 8 F T 500 0 0 ./other_inputs/SpeciesList.csv ./other_inputs/CNS_tabase3HF_France_IdConc.learner T ./other_inputs/Referentiel_seuils_ProbEspHF_.csv 1000 13
cd $TADARIDAC_DIR && $RSCRIPT Ta_Tc.R $INPUT_FILE ClassifEspFrance180303.learner N 8 F T 500 0 0 ./other_inputs/SpeciesList.csv ./other_inputs/CNS_tabase3HF_France_IdConc.learner T ./other_inputs/Referentiel_seuils_ProbEspHF_.csv 1000 14
cd $TADARIDAC_DIR && $RSCRIPT Ta_Tc.R $INPUT_FILE ClassifEspFrance180303.learner N 8 F T 500 0 0 ./other_inputs/SpeciesList.csv ./other_inputs/CNS_tabase3HF_France_IdConc.learner T ./other_inputs/Referentiel_seuils_ProbEspHF_.csv 1000 15
cd $TADARIDAC_DIR && $RSCRIPT Ta_Tc.R $INPUT_FILE ClassifEspFrance180303.learner N 8 F T 500 0 0 ./other_inputs/SpeciesList.csv ./other_inputs/CNS_tabase3HF_France_IdConc.learner T ./other_inputs/Referentiel_seuils_ProbEspHF_.csv 1000 16
cd $TADARIDAC_DIR && $RSCRIPT Ta_Tc.R $INPUT_FILE ClassifEspFrance180303.learner N 8 F T 500 0 0 ./other_inputs/SpeciesList.csv ./other_inputs/CNS_tabase3HF_France_IdConc.learner T ./other_inputs/Referentiel_seuils_ProbEspHF_.csv 1000 17
cd $TADARIDAC_DIR && $RSCRIPT Ta_Tc.R $INPUT_FILE ClassifEspFrance180303.learner N 8 F T 500 0 0 ./other_inputs/SpeciesList.csv ./other_inputs/CNS_tabase3HF_France_IdConc.learner T ./other_inputs/Referentiel_seuils_ProbEspHF_.csv 1000 18
cd $TADARIDAC_DIR && $RSCRIPT Ta_Tc.R $INPUT_FILE ClassifEspFrance180303.learner N 8 F T 500 0 0 ./other_inputs/SpeciesList.csv ./other_inputs/CNS_tabase3HF_France_IdConc.learner T ./other_inputs/Referentiel_seuils_ProbEspHF_.csv 1000 19
cd $TADARIDAC_DIR && $RSCRIPT Ta_Tc.R $INPUT_FILE ClassifEspFrance180303.learner N 8 F T 500 0 0 ./other_inputs/SpeciesList.csv ./other_inputs/CNS_tabase3HF_France_IdConc.learner T ./other_inputs/Referentiel_seuils_ProbEspHF_.csv 1000 20
cd $TADARIDAC_DIR && $RSCRIPT Ta_Tc.R $INPUT_FILE ClassifEspFrance180303.learner N 8 F T 500 0 0 ./other_inputs/SpeciesList.csv ./other_inputs/CNS_tabase3HF_France_IdConc.learner T ./other_inputs/Referentiel_seuils_ProbEspHF_.csv 1000 21
cd $TADARIDAC_DIR && $RSCRIPT Ta_Tc.R $INPUT_FILE ClassifEspFrance180303.learner N 8 F T 500 0 0 ./other_inputs/SpeciesList.csv ./other_inputs/CNS_tabase3HF_France_IdConc.learner T ./other_inputs/Referentiel_seuils_ProbEspHF_.csv 1000 22
cd $TADARIDAC_DIR && $RSCRIPT Ta_Tc.R $INPUT_FILE ClassifEspFrance180303.learner N 8 F T 500 0 0 ./other_inputs/SpeciesList.csv ./other_inputs/CNS_tabase3HF_France_IdConc.learner T ./other_inputs/Referentiel_seuils_ProbEspHF_.csv 1000 23
cd $TADARIDAC_DIR && $RSCRIPT Ta_Tc.R $INPUT_FILE ClassifEspFrance180303.learner N 8 F T 500 0 0 ./other_inputs/SpeciesList.csv ./other_inputs/CNS_tabase3HF_France_IdConc.learner T ./other_inputs/Referentiel_seuils_ProbEspHF_.csv 1000 24
cd $TADARIDAC_DIR && $RSCRIPT Ta_Tc.R $INPUT_FILE ClassifEspFrance180303.learner N 8 F T 500 0 0 ./other_inputs/SpeciesList.csv ./other_inputs/CNS_tabase3HF_France_IdConc.learner T ./other_inputs/Referentiel_seuils_ProbEspHF_.csv 1000 25
cd $TADARIDAC_DIR && $RSCRIPT Ta_Tc.R $INPUT_FILE ClassifEspFrance180303.learner N 8 F T 500 0 0 ./other_inputs/SpeciesList.csv ./other_inputs/CNS_tabase3HF_France_IdConc.learner T ./other_inputs/Referentiel_seuils_ProbEspHF_.csv 1000 26
cd $TADARIDAC_DIR && $RSCRIPT Ta_Tc.R $INPUT_FILE ClassifEspFrance180303.learner N 8 F T 500 0 0 ./other_inputs/SpeciesList.csv ./other_inputs/CNS_tabase3HF_France_IdConc.learner T ./other_inputs/Referentiel_seuils_ProbEspHF_.csv 1000 27
cd $TADARIDAC_DIR && $RSCRIPT Ta_Tc.R $INPUT_FILE ClassifEspFrance180303.learner N 8 F T 500 0 0 ./other_inputs/SpeciesList.csv ./other_inputs/CNS_tabase3HF_France_IdConc.learner T ./other_inputs/Referentiel_seuils_ProbEspHF_.csv 1000 28
cd $TADARIDAC_DIR && $RSCRIPT Ta_Tc.R $INPUT_FILE ClassifEspFrance180303.learner N 8 F T 500 0 0 ./other_inputs/SpeciesList.csv ./other_inputs/CNS_tabase3HF_France_IdConc.learner T ./other_inputs/Referentiel_seuils_ProbEspHF_.csv 1000 29
cd $TADARIDAC_DIR && $RSCRIPT Ta_Tc.R $INPUT_FILE ClassifEspFrance180303.learner N 8 F T 500 0 0 ./other_inputs/SpeciesList.csv ./other_inputs/CNS_tabase3HF_France_IdConc.learner T ./other_inputs/Referentiel_seuils_ProbEspHF_.csv 1000 30
cd $TADARIDAC_DIR && $RSCRIPT Ta_Tc.R $INPUT_FILE ClassifEspFrance180303.learner N 8 F T 500 0 0 ./other_inputs/SpeciesList.csv ./other_inputs/CNS_tabase3HF_France_IdConc.learner T ./other_inputs/Referentiel_seuils_ProbEspHF_.csv 1000 31
cd $TADARIDAC_DIR && $RSCRIPT Ta_Tc.R $INPUT_FILE ClassifEspFrance180303.learner N 8 F T 500 0 0 ./other_inputs/SpeciesList.csv ./other_inputs/CNS_tabase3HF_France_IdConc.learner T ./other_inputs/Referentiel_seuils_ProbEspHF_.csv 1000 32
cd $TADARIDAC_DIR && $RSCRIPT Ta_Tc.R $INPUT_FILE ClassifEspFrance180303.learner N 8 F T 500 0 0 ./other_inputs/SpeciesList.csv ./other_inputs/CNS_tabase3HF_France_IdConc.learner T ./other_inputs/Referentiel_seuils_ProbEspHF_.csv 1000 33
cd $TADARIDAC_DIR && $RSCRIPT Ta_Tc.R $INPUT_FILE ClassifEspFrance180303.learner N 8 F T 500 0 0 ./other_inputs/SpeciesList.csv ./other_inputs/CNS_tabase3HF_France_IdConc.learner T ./other_inputs/Referentiel_seuils_ProbEspHF_.csv 1000 34
cd $TADARIDAC_DIR && $RSCRIPT Ta_Tc.R $INPUT_FILE ClassifEspFrance180303.learner N 8 F T 500 0 0 ./other_inputs/SpeciesList.csv ./other_inputs/CNS_tabase3HF_France_IdConc.learner T ./other_inputs/Referentiel_seuils_ProbEspHF_.csv 1000 35
cd $TADARIDAC_DIR && $RSCRIPT Ta_Tc.R $INPUT_FILE ClassifEspFrance180303.learner N 8 F T 500 0 0 ./other_inputs/SpeciesList.csv ./other_inputs/CNS_tabase3HF_France_IdConc.learner T ./other_inputs/Referentiel_seuils_ProbEspHF_.csv 1000 36
cd $TADARIDAC_DIR && $RSCRIPT Ta_Tc.R $INPUT_FILE ClassifEspFrance180303.learner N 8 F T 500 0 0 ./other_inputs/SpeciesList.csv ./other_inputs/CNS_tabase3HF_France_IdConc.learner T ./other_inputs/Referentiel_seuils_ProbEspHF_.csv 1000 37
cd $TADARIDAC_DIR && $RSCRIPT Ta_Tc.R $INPUT_FILE ClassifEspFrance180303.learner N 8 F T 500 0 0 ./other_inputs/SpeciesList.csv ./other_inputs/CNS_tabase3HF_France_IdConc.learner T ./other_inputs/Referentiel_seuils_ProbEspHF_.csv 1000 38
cd $TADARIDAC_DIR && $RSCRIPT Ta_Tc.R $INPUT_FILE ClassifEspFrance180303.learner N 8 F T 500 0 0 ./other_inputs/SpeciesList.csv ./other_inputs/CNS_tabase3HF_France_IdConc.learner T ./other_inputs/Referentiel_seuils_ProbEspHF_.csv 1000 39
cd $TADARIDAC_DIR && $RSCRIPT Ta_Tc.R $INPUT_FILE ClassifEspFrance180303.learner N 8 F T 500 0 0 ./other_inputs/SpeciesList.csv ./other_inputs/CNS_tabase3HF_France_IdConc.learner T ./other_inputs/Referentiel_seuils_ProbEspHF_.csv 1000 40
cd $TADARIDAC_DIR && $RSCRIPT Ta_Tc.R $INPUT_FILE ClassifEspFrance180303.learner N 8 F T 500 0 0 ./other_inputs/SpeciesList.csv ./other_inputs/CNS_tabase3HF_France_IdConc.learner T ./other_inputs/Referentiel_seuils_ProbEspHF_.csv 1000 41
cd $TADARIDAC_DIR && $RSCRIPT Ta_Tc.R $INPUT_FILE ClassifEspFrance180303.learner N 8 F T 500 0 0 ./other_inputs/SpeciesList.csv ./other_inputs/CNS_tabase3HF_France_IdConc.learner T ./other_inputs/Referentiel_seuils_ProbEspHF_.csv 1000 42
cd $TADARIDAC_DIR && $RSCRIPT Ta_Tc.R $INPUT_FILE ClassifEspFrance180303.learner N 8 F T 500 0 0 ./other_inputs/SpeciesList.csv ./other_inputs/CNS_tabase3HF_France_IdConc.learner T ./other_inputs/Referentiel_seuils_ProbEspHF_.csv 1000 43
cd $TADARIDAC_DIR && $RSCRIPT Ta_Tc.R $INPUT_FILE ClassifEspFrance180303.learner N 8 F T 500 0 0 ./other_inputs/SpeciesList.csv ./other_inputs/CNS_tabase3HF_France_IdConc.learner T ./other_inputs/Referentiel_seuils_ProbEspHF_.csv 1000 44
cd $TADARIDAC_DIR && $RSCRIPT Ta_Tc.R $INPUT_FILE ClassifEspFrance180303.learner N 8 F T 500 0 0 ./other_inputs/SpeciesList.csv ./other_inputs/CNS_tabase3HF_France_IdConc.learner T ./other_inputs/Referentiel_seuils_ProbEspHF_.csv 1000 45
cd $TADARIDAC_DIR && $RSCRIPT Ta_Tc.R $INPUT_FILE ClassifEspFrance180303.learner N 8 F T 500 0 0 ./other_inputs/SpeciesList.csv ./other_inputs/CNS_tabase3HF_France_IdConc.learner T ./other_inputs/Referentiel_seuils_ProbEspHF_.csv 1000 46
cd $TADARIDAC_DIR && $RSCRIPT Ta_Tc.R $INPUT_FILE ClassifEspFrance180303.learner N 8 F T 500 0 0 ./other_inputs/SpeciesList.csv ./other_inputs/CNS_tabase3HF_France_IdConc.learner T ./other_inputs/Referentiel_seuils_ProbEspHF_.csv 1000 47
cd $TADARIDAC_DIR && $RSCRIPT Ta_Tc.R $INPUT_FILE ClassifEspFrance180303.learner N 8 F T 500 0 0 ./other_inputs/SpeciesList.csv ./other_inputs/CNS_tabase3HF_France_IdConc.learner T ./other_inputs/Referentiel_seuils_ProbEspHF_.csv 1000 48
cd $TADARIDAC_DIR && $RSCRIPT Ta_Tc.R $INPUT_FILE ClassifEspFrance180303.learner N 8 F T 500 0 0 ./other_inputs/SpeciesList.csv ./other_inputs/CNS_tabase3HF_France_IdConc.learner T ./other_inputs/Referentiel_seuils_ProbEspHF_.csv 1000 49
cd $TADARIDAC_DIR && $RSCRIPT Ta_Tc.R $INPUT_FILE ClassifEspFrance180303.learner N 8 F T 500 0 0 ./other_inputs/SpeciesList.csv ./other_inputs/CNS_tabase3HF_France_IdConc.learner T ./other_inputs/Referentiel_seuils_ProbEspHF_.csv 1000 50
cd $TADARIDAC_DIR && $RSCRIPT Ta_Tc.R $INPUT_FILE ClassifEspFrance180303.learner N 8 F T 500 0 0 ./other_inputs/SpeciesList.csv ./other_inputs/CNS_tabase3HF_France_IdConc.learner T ./other_inputs/Referentiel_seuils_ProbEspHF_.csv 1000 51
cd $TADARIDAC_DIR && $RSCRIPT Ta_Tc.R $INPUT_FILE ClassifEspFrance180303.learner N 8 F T 500 0 0 ./other_inputs/SpeciesList.csv ./other_inputs/CNS_tabase3HF_France_IdConc.learner T ./other_inputs/Referentiel_seuils_ProbEspHF_.csv 1000 52
cd $TADARIDAC_DIR && $RSCRIPT Ta_Tc.R $INPUT_FILE ClassifEspFrance180303.learner N 8 F T 500 0 0 ./other_inputs/SpeciesList.csv ./other_inputs/CNS_tabase3HF_France_IdConc.learner T ./other_inputs/Referentiel_seuils_ProbEspHF_.csv 1000 53
cd $TADARIDAC_DIR && $RSCRIPT Ta_Tc.R $INPUT_FILE ClassifEspFrance180303.learner N 8 F T 500 0 0 ./other_inputs/SpeciesList.csv ./other_inputs/CNS_tabase3HF_France_IdConc.learner T ./other_inputs/Referentiel_seuils_ProbEspHF_.csv 1000 54
cd $TADARIDAC_DIR && $RSCRIPT Ta_Tc.R $INPUT_FILE ClassifEspFrance180303.learner N 8 F T 500 0 0 ./other_inputs/SpeciesList.csv ./other_inputs/CNS_tabase3HF_France_IdConc.learner T ./other_inputs/Referentiel_seuils_ProbEspHF_.csv 1000 55
cd $TADARIDAC_DIR && $RSCRIPT Ta_Tc.R $INPUT_FILE ClassifEspFrance180303.learner N 8 F T 500 0 0 ./other_inputs/SpeciesList.csv ./other_inputs/CNS_tabase3HF_France_IdConc.learner T ./other_inputs/Referentiel_seuils_ProbEspHF_.csv 1000 56
cd $TADARIDAC_DIR && $RSCRIPT Ta_Tc.R $INPUT_FILE ClassifEspFrance180303.learner N 8 F T 500 0 0 ./other_inputs/SpeciesList.csv ./other_inputs/CNS_tabase3HF_France_IdConc.learner T ./other_inputs/Referentiel_seuils_ProbEspHF_.csv 1000 57
cd $TADARIDAC_DIR && $RSCRIPT Ta_Tc.R $INPUT_FILE ClassifEspFrance180303.learner N 8 F T 500 0 0 ./other_inputs/SpeciesList.csv ./other_inputs/CNS_tabase3HF_France_IdConc.learner T ./other_inputs/Referentiel_seuils_ProbEspHF_.csv 1000 58
cd $TADARIDAC_DIR && $RSCRIPT Ta_Tc.R $INPUT_FILE ClassifEspFrance180303.learner N 8 F T 500 0 0 ./other_inputs/SpeciesList.csv ./other_inputs/CNS_tabase3HF_France_IdConc.learner T ./other_inputs/Referentiel_seuils_ProbEspHF_.csv 1000 59
cd $TADARIDAC_DIR && $RSCRIPT Ta_Tc.R $INPUT_FILE ClassifEspFrance180303.learner N 8 F T 500 0 0 ./other_inputs/SpeciesList.csv ./other_inputs/CNS_tabase3HF_France_IdConc.learner T ./other_inputs/Referentiel_seuils_ProbEspHF_.csv 1000 60
cd $TADARIDAC_DIR && $RSCRIPT Ta_Tc.R $INPUT_FILE ClassifEspFrance180303.learner N 8 F T 500 0 0 ./other_inputs/SpeciesList.csv ./other_inputs/CNS_tabase3HF_France_IdConc.learner T ./other_inputs/Referentiel_seuils_ProbEspHF_.csv 1000 61
cd $TADARIDAC_DIR && $RSCRIPT Ta_Tc.R $INPUT_FILE ClassifEspFrance180303.learner N 8 F T 500 0 0 ./other_inputs/SpeciesList.csv ./other_inputs/CNS_tabase3HF_France_IdConc.learner T ./other_inputs/Referentiel_seuils_ProbEspHF_.csv 1000 62
cd $TADARIDAC_DIR && $RSCRIPT Ta_Tc.R $INPUT_FILE ClassifEspFrance180303.learner N 8 F T 500 0 0 ./other_inputs/SpeciesList.csv ./other_inputs/CNS_tabase3HF_France_IdConc.learner T ./other_inputs/Referentiel_seuils_ProbEspHF_.csv 1000 63
cd $TADARIDAC_DIR && $RSCRIPT Ta_Tc.R $INPUT_FILE ClassifEspFrance180303.learner N 8 F T 500 0 0 ./other_inputs/SpeciesList.csv ./other_inputs/CNS_tabase3HF_France_IdConc.learner T ./other_inputs/Referentiel_seuils_ProbEspHF_.csv 1000 64
cd $TADARIDAC_DIR && $RSCRIPT Ta_Tc.R $INPUT_FILE ClassifEspFrance180303.learner N 8 F T 500 0 0 ./other_inputs/SpeciesList.csv ./other_inputs/CNS_tabase3HF_France_IdConc.learner T ./other_inputs/Referentiel_seuils_ProbEspHF_.csv 1000 65
cd $TADARIDAC_DIR && $RSCRIPT Ta_Tc.R $INPUT_FILE ClassifEspFrance180303.learner N 8 F T 500 0 0 ./other_inputs/SpeciesList.csv ./other_inputs/CNS_tabase3HF_France_IdConc.learner T ./other_inputs/Referentiel_seuils_ProbEspHF_.csv 1000 66
cd $TADARIDAC_DIR && $RSCRIPT Ta_Tc.R $INPUT_FILE ClassifEspFrance180303.learner N 8 F T 500 0 0 ./other_inputs/SpeciesList.csv ./other_inputs/CNS_tabase3HF_France_IdConc.learner T ./other_inputs/Referentiel_seuils_ProbEspHF_.csv 1000 67
cd $TADARIDAC_DIR && $RSCRIPT Ta_Tc.R $INPUT_FILE ClassifEspFrance180303.learner N 8 F T 500 0 0 ./other_inputs/SpeciesList.csv ./other_inputs/CNS_tabase3HF_France_IdConc.learner T ./other_inputs/Referentiel_seuils_ProbEspHF_.csv 1000 68
cd $TADARIDAC_DIR && $RSCRIPT Ta_Tc.R $INPUT_FILE ClassifEspFrance180303.learner N 8 F T 500 0 0 ./other_inputs/SpeciesList.csv ./other_inputs/CNS_tabase3HF_France_IdConc.learner T ./other_inputs/Referentiel_seuils_ProbEspHF_.csv 1000 69
cd $TADARIDAC_DIR && $RSCRIPT Ta_Tc.R $INPUT_FILE ClassifEspFrance180303.learner N 8 F T 500 0 0 ./other_inputs/SpeciesList.csv ./other_inputs/CNS_tabase3HF_France_IdConc.learner T ./other_inputs/Referentiel_seuils_ProbEspHF_.csv 1000 70
cd $TADARIDAC_DIR && $RSCRIPT Ta_Tc.R $INPUT_FILE ClassifEspFrance180303.learner N 8 F T 500 0 0 ./other_inputs/SpeciesList.csv ./other_inputs/CNS_tabase3HF_France_IdConc.learner T ./other_inputs/Referentiel_seuils_ProbEspHF_.csv 1000 71
cd $TADARIDAC_DIR && $RSCRIPT Ta_Tc.R $INPUT_FILE ClassifEspFrance180303.learner N 8 F T 500 0 0 ./other_inputs/SpeciesList.csv ./other_inputs/CNS_tabase3HF_France_IdConc.learner T ./other_inputs/Referentiel_seuils_ProbEspHF_.csv 1000 72
cd $TADARIDAC_DIR && $RSCRIPT Ta_Tc.R $INPUT_FILE ClassifEspFrance180303.learner N 8 F T 500 0 0 ./other_inputs/SpeciesList.csv ./other_inputs/CNS_tabase3HF_France_IdConc.learner T ./other_inputs/Referentiel_seuils_ProbEspHF_.csv 1000 73
cd $TADARIDAC_DIR && $RSCRIPT Ta_Tc.R $INPUT_FILE ClassifEspFrance180303.learner N 8 F T 500 0 0 ./other_inputs/SpeciesList.csv ./other_inputs/CNS_tabase3HF_France_IdConc.learner T ./other_inputs/Referentiel_seuils_ProbEspHF_.csv 1000 74
cd $TADARIDAC_DIR && $RSCRIPT Ta_Tc.R $INPUT_FILE ClassifEspFrance180303.learner N 8 F T 500 0 0 ./other_inputs/SpeciesList.csv ./other_inputs/CNS_tabase3HF_France_IdConc.learner T ./other_inputs/Referentiel_seuils_ProbEspHF_.csv 1000 75
cd $TADARIDAC_DIR && $RSCRIPT Ta_Tc.R $INPUT_FILE ClassifEspFrance180303.learner N 8 F T 500 0 0 ./other_inputs/SpeciesList.csv ./other_inputs/CNS_tabase3HF_France_IdConc.learner T ./other_inputs/Referentiel_seuils_ProbEspHF_.csv 1000 76
cd $TADARIDAC_DIR && $RSCRIPT Ta_Tc.R $INPUT_FILE ClassifEspFrance180303.learner N 8 F T 500 0 0 ./other_inputs/SpeciesList.csv ./other_inputs/CNS_tabase3HF_France_IdConc.learner T ./other_inputs/Referentiel_seuils_ProbEspHF_.csv 1000 77
cd $TADARIDAC_DIR && $RSCRIPT Ta_Tc.R $INPUT_FILE ClassifEspFrance180303.learner N 8 F T 500 0 0 ./other_inputs/SpeciesList.csv ./other_inputs/CNS_tabase3HF_France_IdConc.learner T ./other_inputs/Referentiel_seuils_ProbEspHF_.csv 1000 78
cd $TADARIDAC_DIR && $RSCRIPT Ta_Tc.R $INPUT_FILE ClassifEspFrance180303.learner N 8 F T 500 0 0 ./other_inputs/SpeciesList.csv ./other_inputs/CNS_tabase3HF_France_IdConc.learner T ./other_inputs/Referentiel_seuils_ProbEspHF_.csv 1000 79
cd $TADARIDAC_DIR && $RSCRIPT Ta_Tc.R $INPUT_FILE ClassifEspFrance180303.learner N 8 F T 500 0 0 ./other_inputs/SpeciesList.csv ./other_inputs/CNS_tabase3HF_France_IdConc.learner T ./other_inputs/Referentiel_seuils_ProbEspHF_.csv 1000 80

cd $TADARIDAC_DIR && $RSCRIPT ContextualClassif.R $INPUT_FILE ./other_inputs/SpeciesList.csv ./other_inputs/ClassifEspC3_2019-03-25.learner f_CombineProbas.R f_Rescale_Probas.r ./other_inputs/Referentiel_seuils_ProbEspC3_2019-03-25_G7__D_G.csv